/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author min
 */
public class BeerView extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public BeerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBeerView = new javax.swing.JPanel();
        jPanelListBeerView = new javax.swing.JPanel();
        jLabelException1BeerView = new javax.swing.JLabel();
        jLabelSumBeerView = new javax.swing.JLabel();
        jLabelMoneyBeerView = new javax.swing.JLabel();
        jLabelVNDBeerView = new javax.swing.JLabel();
        jButtonAddBeerView = new javax.swing.JButton();
        jScrollPaneException1BeerView = new javax.swing.JScrollPane();
        jTableMenuOfBeer = new javax.swing.JTable();
        jButtonBackBeerException1 = new javax.swing.JButton();
        jLabelImageBeerView = new javax.swing.JLabel();
        jButtonBackBeer = new javax.swing.JButton();
        jPanelPaymentMethodsBeerView = new javax.swing.JPanel();
        jLabelPaymentMethodsBeerView = new javax.swing.JLabel();
        jButtonPayWithQRCodeBeerView = new javax.swing.JButton();
        jButtonPayInCashBeerView = new javax.swing.JButton();
        jPanelContainerBeerView = new javax.swing.JPanel();
        jTextFieldNameBeerView = new javax.swing.JTextField();
        jLabelPositionBeerView = new javax.swing.JLabel();
        jPaneContainStarBeerView = new javax.swing.JPanel();
        jLabelStar1BeerView = new javax.swing.JLabel();
        jLabelStar2BeerView = new javax.swing.JLabel();
        jLabelStar3BeerView = new javax.swing.JLabel();
        jLabelStar4BeerView = new javax.swing.JLabel();
        jPanelException1BeerView = new javax.swing.JPanel();
        jLabelGreenDotBeer = new javax.swing.JLabel();
        jLabelTimeOpenBeerView = new javax.swing.JLabel();
        jPanelHourOpenBeer = new javax.swing.JPanel();
        jLabelHourOpenBeer = new javax.swing.JLabel();
        jLabelUpToBeerView = new javax.swing.JLabel();
        jButtonFavoriteBeerView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBeerView.setBackground(new java.awt.Color(255, 153, 51));
        jPanelBeerView.setPreferredSize(new java.awt.Dimension(861, 624));

        jPanelListBeerView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelSumBeerView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSumBeerView.setText("Tổng:");

        jLabelMoneyBeerView.setText("                                                   0");
        jLabelMoneyBeerView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVNDBeerView.setText("VNĐ");

        jButtonAddBeerView.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAddBeerView.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonAddBeerView.setText("Thêm");
        jButtonAddBeerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBeerViewActionPerformed(evt);
            }
        });

        jTableMenuOfBeer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Bia tiger", "20,000",  new Integer(0)},
                {"2", "Bia Sài Gòn", "16,000",  new Integer(0)},
                {"3", "Tiger crystal", "22,000",  new Integer(0)},
                {"4", "Sài Gòn special", "18,000",  new Integer(0)},
                {"5", "Couple combo:2 beers + đậu nành Nhật + chân gà sả tắc/phô mai xông khói/jambon", "199,000",  new Integer(0)},
                {"6", "Smoke combo: 4 beers + khô gà/đậu nành Nhật/đậu phộng", "499,000",  new Integer(0)},
                {"7", "Chill combo: 4 beers + jambon + đậu phộng + bắp bò/cánh gà sốt Thái", "399,000",  new Integer(0)},
                {"8", "Party combo: 6 beers + đậu nành Nhật + đậu phộng + chân gà sả tắc + bắp bò Savoury + khô bò sả ớt + cánh gà sốt cay", "599,000",  new Integer(0)},
                {"9", "Budweiser (độ cồn: 5%)", "40,000",  new Integer(0)},
                {"10", "Singha (độ cồn: 5%)", "45,000",  new Integer(0)},
                {"11", "Leffe Brune Bruin (độ cồn: 6.5%)", "80,000",  new Integer(0)},
                {"12", "Leffe Blonde Blond(độ cồn: 6.6%)", "70,000",  new Integer(0)},
                {"13", "Stella Artois(độ cồn: 5%)", "70,000",  new Integer(0)},
                {"14", "Jopen Hoppen (độ cồn: 6.8%)", "80,000",  new Integer(0)},
                {"15", "Jopen Gerstebier (độ cồn: 4.9%)", "80,000",  new Integer(0)},
                {"16", "Jopen Jacobus RPA (độ cồn: 5.5%)", "80,000",  new Integer(0)},
                {"17", "Jopen Adriaan Wit (độ cồn: 5%)", "80,000",  new Integer(0)},
                {"18", "U Beer(độ cồn: 5%)", "45,000",  new Integer(0)},
                {"19", "Royal Dutch(độ cồn: 12%)", "85,000",  new Integer(0)},
                {"20", "Heineken(độ cồn: 5%)", "40,000",  new Integer(0)},
                {"21", "Corona(độ cồn: 4.6%)", "55,000",  new Integer(0)},
                {"22", "Coronita(độ cồn: 4.6%)", "40,000",  new Integer(0)},
                {"23", "Hoegaarden white(độ cồn: 4.9%)", "55,000",  new Integer(0)},
                {"24", "East West IPA(độ cồn: 6.7%)", "80,000",  new Integer(0)},
                {"25", "Estrella(độ cồn: 4.6%)", "70,000",  new Integer(0)},
                {"26", "Bear Beer(độ cồn: 12%)", "85,000",  new Integer(0)},
                {"27", "Bundaberg Fruit", "85,000",  new Integer(0)},
                {"28", "Hoegaarden Rosee(độ cồn: 3%)", "55,000",  new Integer(0)},
                {"29", "Oettinger(độ cồn: 0.5%)", "80,000",  new Integer(0)},
                {"30", "Magners Berry Cider(độ cồn: 4.5%)", "80,000",  new Integer(0)},
                {"31", "Magners Original Apple(độ cồn: 4.5%)", "80,000",  new Integer(0)},
                {"32", "Magners Pear(độ cồn: 4.5%)", "80,000",  new Integer(0)},
                {"33", "Chimay Red(độ cồn: 7%)", "220,000",  new Integer(0)},
                {"34", "Chimay Blue(độ cồn: 9%)", "220,000",  new Integer(0)},
                {"35", "Kasteel Triple(độ cồn: 11%)", "220,000",  new Integer(0)},
                {"36", "Kasteel Rouge(độ cồn: 8%)", "220,000",  new Integer(0)},
                {"37", "Kasteel Cuvee(độ cồn: 11%)", "230,000",  new Integer(0)},
                {"38", "Kasteel Donker(độ cồn: 11%)", "230,000",  new Integer(0)}
            },
            new String [] {
                "Số thứ tự", "Tên", "Giá (VNĐ)", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneException1BeerView.setViewportView(jTableMenuOfBeer);
        if (jTableMenuOfBeer.getColumnModel().getColumnCount() > 0) {
            jTableMenuOfBeer.getColumnModel().getColumn(0).setResizable(false);
            jTableMenuOfBeer.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMenuOfBeer.getColumnModel().getColumn(1).setResizable(false);
            jTableMenuOfBeer.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableMenuOfBeer.getColumnModel().getColumn(2).setResizable(false);
            jTableMenuOfBeer.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanelListBeerViewLayout = new javax.swing.GroupLayout(jPanelListBeerView);
        jPanelListBeerView.setLayout(jPanelListBeerViewLayout);
        jPanelListBeerViewLayout.setHorizontalGroup(
            jPanelListBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListBeerViewLayout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addComponent(jLabelException1BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(jPanelListBeerViewLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButtonAddBeerView)
                .addGap(103, 103, 103)
                .addComponent(jLabelSumBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMoneyBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVNDBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelListBeerViewLayout.createSequentialGroup()
                .addComponent(jScrollPaneException1BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanelListBeerViewLayout.setVerticalGroup(
            jPanelListBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListBeerViewLayout.createSequentialGroup()
                .addComponent(jLabelException1BeerView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneException1BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelListBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMoneyBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAddBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabelSumBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVNDBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonBackBeerException1.setBorder(null);

        jLabelImageBeerView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\BeerView.jpg")); // NOI18N
        jLabelImageBeerView.setText("jLabel1");

        jButtonBackBeer.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackBeer.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-back-64.png")); // NOI18N
        jButtonBackBeer.setBorder(null);
        jButtonBackBeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackBeerActionPerformed(evt);
            }
        });

        jLabelPaymentMethodsBeerView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPaymentMethodsBeerView.setText("      Phương thức thanh toán");

        jButtonPayWithQRCodeBeerView.setBackground(new java.awt.Color(51, 255, 0));
        jButtonPayWithQRCodeBeerView.setText("Quét mã QR");
        jButtonPayWithQRCodeBeerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayWithQRCodeBeerViewActionPerformed(evt);
            }
        });

        jButtonPayInCashBeerView.setBackground(new java.awt.Color(102, 255, 0));
        jButtonPayInCashBeerView.setText("Sử dụng tiền mặt");

        javax.swing.GroupLayout jPanelPaymentMethodsBeerViewLayout = new javax.swing.GroupLayout(jPanelPaymentMethodsBeerView);
        jPanelPaymentMethodsBeerView.setLayout(jPanelPaymentMethodsBeerViewLayout);
        jPanelPaymentMethodsBeerViewLayout.setHorizontalGroup(
            jPanelPaymentMethodsBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsBeerViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPaymentMethodsBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentMethodsBeerViewLayout.createSequentialGroup()
                        .addGroup(jPanelPaymentMethodsBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPayWithQRCodeBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPayInCashBeerView))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentMethodsBeerViewLayout.createSequentialGroup()
                        .addComponent(jLabelPaymentMethodsBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanelPaymentMethodsBeerViewLayout.setVerticalGroup(
            jPanelPaymentMethodsBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsBeerViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaymentMethodsBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(jButtonPayInCashBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPayWithQRCodeBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanelContainerBeerView.setBackground(new java.awt.Color(255, 153, 51));
        jPanelContainerBeerView.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jTextFieldNameBeerView.setBackground(new java.awt.Color(255, 153, 51));
        jTextFieldNameBeerView.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNameBeerView.setText("Lão Hạc Quán - Beer & Cafe");
        jTextFieldNameBeerView.setBorder(null);
        jTextFieldNameBeerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameBeerViewActionPerformed(evt);
            }
        });

        jLabelPositionBeerView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPositionBeerView.setText("Địa điểm: ao sen ngõ số 2");

        jPaneContainStarBeerView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelStar1BeerView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar1BeerView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar2BeerView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar2BeerView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar3BeerView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar3BeerView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar4BeerView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar4BeerView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        javax.swing.GroupLayout jPaneContainStarBeerViewLayout = new javax.swing.GroupLayout(jPaneContainStarBeerView);
        jPaneContainStarBeerView.setLayout(jPaneContainStarBeerViewLayout);
        jPaneContainStarBeerViewLayout.setHorizontalGroup(
            jPaneContainStarBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarBeerViewLayout.createSequentialGroup()
                .addComponent(jLabelStar1BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar2BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar3BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar4BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 137, Short.MAX_VALUE))
        );
        jPaneContainStarBeerViewLayout.setVerticalGroup(
            jPaneContainStarBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarBeerViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPaneContainStarBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStar1BeerView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStar2BeerView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStar3BeerView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStar4BeerView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelException1BeerView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelGreenDotBeer.setBackground(new java.awt.Color(255, 102, 0));
        jLabelGreenDotBeer.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-green-circle-48.png")); // NOI18N

        jLabelTimeOpenBeerView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelTimeOpenBeerView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimeOpenBeerView.setText("Mở cửa 8a.m - 6p.m ");

        javax.swing.GroupLayout jPanelException1BeerViewLayout = new javax.swing.GroupLayout(jPanelException1BeerView);
        jPanelException1BeerView.setLayout(jPanelException1BeerViewLayout);
        jPanelException1BeerViewLayout.setHorizontalGroup(
            jPanelException1BeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelException1BeerViewLayout.createSequentialGroup()
                .addComponent(jLabelGreenDotBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTimeOpenBeerView)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanelException1BeerViewLayout.setVerticalGroup(
            jPanelException1BeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGreenDotBeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTimeOpenBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelHourOpenBeer.setBackground(new java.awt.Color(255, 153, 51));

        jLabelHourOpenBeer.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-coins-64.png")); // NOI18N

        jLabelUpToBeerView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUpToBeerView.setText("15,000 - 250,000 VNĐ");

        javax.swing.GroupLayout jPanelHourOpenBeerLayout = new javax.swing.GroupLayout(jPanelHourOpenBeer);
        jPanelHourOpenBeer.setLayout(jPanelHourOpenBeerLayout);
        jPanelHourOpenBeerLayout.setHorizontalGroup(
            jPanelHourOpenBeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHourOpenBeerLayout.createSequentialGroup()
                .addComponent(jLabelHourOpenBeer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUpToBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelHourOpenBeerLayout.setVerticalGroup(
            jPanelHourOpenBeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHourOpenBeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUpToBeerView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButtonFavoriteBeerView.setBackground(new java.awt.Color(255, 0, 51));
        jButtonFavoriteBeerView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\Favorite.png")); // NOI18N
        jButtonFavoriteBeerView.setBorder(null);
        jButtonFavoriteBeerView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavoriteBeerViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerBeerViewLayout = new javax.swing.GroupLayout(jPanelContainerBeerView);
        jPanelContainerBeerView.setLayout(jPanelContainerBeerViewLayout);
        jPanelContainerBeerViewLayout.setHorizontalGroup(
            jPanelContainerBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerBeerViewLayout.createSequentialGroup()
                .addGroup(jPanelContainerBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelException1BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPaneContainStarBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHourOpenBeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelContainerBeerViewLayout.createSequentialGroup()
                .addGroup(jPanelContainerBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPositionBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFavoriteBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 148, Short.MAX_VALUE))
        );
        jPanelContainerBeerViewLayout.setVerticalGroup(
            jPanelContainerBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerBeerViewLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jButtonFavoriteBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNameBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPositionBeerView)
                .addGap(10, 10, 10)
                .addComponent(jPaneContainStarBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelException1BeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHourOpenBeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelBeerViewLayout = new javax.swing.GroupLayout(jPanelBeerView);
        jPanelBeerView.setLayout(jPanelBeerViewLayout);
        jPanelBeerViewLayout.setHorizontalGroup(
            jPanelBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelBeerViewLayout.createSequentialGroup()
                .addGap(0, 318, Short.MAX_VALUE)
                .addComponent(jPanelContainerBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBackBeerException1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBackBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelBeerViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPaymentMethodsBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBeerViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelListBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelImageBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        jPanelBeerViewLayout.setVerticalGroup(
            jPanelBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBeerViewLayout.createSequentialGroup()
                .addGroup(jPanelBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBeerViewLayout.createSequentialGroup()
                        .addComponent(jButtonBackBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBackBeerException1)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBeerViewLayout.createSequentialGroup()
                        .addComponent(jPanelContainerBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanelPaymentMethodsBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelBeerViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBeerViewLayout.createSequentialGroup()
                    .addComponent(jLabelImageBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBeerView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBeerView, javax.swing.GroupLayout.PREFERRED_SIZE, 603, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddBeerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBeerViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddBeerViewActionPerformed

    private void jButtonPayWithQRCodeBeerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayWithQRCodeBeerViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayWithQRCodeBeerViewActionPerformed

    private void jTextFieldNameBeerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameBeerViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameBeerViewActionPerformed

    private void jButtonFavoriteBeerViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavoriteBeerViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFavoriteBeerViewActionPerformed

    private void jButtonBackBeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackBeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackBeerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBeerView;
    private javax.swing.JButton jButtonBackBeer;
    private javax.swing.JButton jButtonBackBeerException1;
    private javax.swing.JButton jButtonFavoriteBeerView;
    private javax.swing.JButton jButtonPayInCashBeerView;
    private javax.swing.JButton jButtonPayWithQRCodeBeerView;
    private javax.swing.JLabel jLabelException1BeerView;
    private javax.swing.JLabel jLabelGreenDotBeer;
    private javax.swing.JLabel jLabelHourOpenBeer;
    private javax.swing.JLabel jLabelImageBeerView;
    private javax.swing.JLabel jLabelMoneyBeerView;
    private javax.swing.JLabel jLabelPaymentMethodsBeerView;
    private javax.swing.JLabel jLabelPositionBeerView;
    private javax.swing.JLabel jLabelStar1BeerView;
    private javax.swing.JLabel jLabelStar2BeerView;
    private javax.swing.JLabel jLabelStar3BeerView;
    private javax.swing.JLabel jLabelStar4BeerView;
    private javax.swing.JLabel jLabelSumBeerView;
    private javax.swing.JLabel jLabelTimeOpenBeerView;
    private javax.swing.JLabel jLabelUpToBeerView;
    private javax.swing.JLabel jLabelVNDBeerView;
    private javax.swing.JPanel jPaneContainStarBeerView;
    private javax.swing.JPanel jPanelBeerView;
    private javax.swing.JPanel jPanelContainerBeerView;
    private javax.swing.JPanel jPanelException1BeerView;
    private javax.swing.JPanel jPanelHourOpenBeer;
    private javax.swing.JPanel jPanelListBeerView;
    private javax.swing.JPanel jPanelPaymentMethodsBeerView;
    private javax.swing.JScrollPane jScrollPaneException1BeerView;
    private javax.swing.JTable jTableMenuOfBeer;
    private javax.swing.JTextField jTextFieldNameBeerView;
    // End of variables declaration//GEN-END:variables
}
