/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author min
 */
public class BillView extends javax.swing.JFrame {

    /**
     * Creates new form BillView
     */
    public BillView() {
        initComponents();
        init();
    }
    
    public void init(){
        setTime();
        //invoice();
    }
    private static String getTime="";
    private static String getDate="";
    int checkGet=0;
    
    public void setTime(){
        new Thread(new Runnable(){
            @Override
            public void run(){
                while (true){
                    try{
                        Thread.sleep(1000);
                    }catch(InterruptedException ex){

                    }
                    Date date = new Date();
                    SimpleDateFormat tf = new SimpleDateFormat("h:mm:ss aa");
                    SimpleDateFormat df = new SimpleDateFormat("EEEE, dd-MM-yyyy");
                    String time = tf.format(date);
                    jLabelTimeBillView.setText(time.split(" ")[0]+" "+time.split(" ")[1]);
                    jLabelDateBillView.setText(df.format(date));
                    if (checkGet == 0){
                        getTime = tf.format(date);
                        System.out.println(getTime);
                        getDate= df.format(date);
                        checkGet=1;
                        jTextAreaCenterBillView.setText("                                                        FastFood\n"
                                                       +"                                              CLB LẬP TRÌNH PTIT\n"
                                                       +"                                            LẬP TRÌNH TỪ TRÁI TIM\n"
                                                       +"                                                 Hotline:0369288612\n"
                                                       +"                                                 PHIẾU TÍNH TIỀN\n"
                                                       +"Time: "+getTime+"     Date: "+getDate+"\n"
                                                       +"Description                                                                                VAT\n"
                                                       +"-------------------------------------------------------------------------------------------\n"
                        );
                        
                    }
                }
            }
        }).start();      
    }
    public void invoice(){
        jTextAreaCenterBillView.setText("                                                 Bill Account\n"
        +"Time: "+getTime+" Date: "+getDate+"\n"
        +"****************************************************************************\n"
        );       
    }
    
//    private void updateInvoice(){
//        for (int i = 0; i < jTableMenuOfBeer.getRowCount(); i++) {
//            String value = (String) jTableMenuOfBeer.getValueAt(i, 3);
//            try{
//                if (value.isEmpty()==false && !"null".equals(value)){
//                    jTextAreaCenterBillView.setText(jTextAreaCenterBillView.getText()+"")
//                }
//                else break;
//            }catch(Exception e){
//                //e.printStackTrace();
//            }
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBillView = new javax.swing.JPanel();
        jPanelHorizontalBillView = new javax.swing.JPanel();
        jButtonBackBillView = new javax.swing.JButton();
        jLabelNameAppBillView = new javax.swing.JLabel();
        jPanelWordBillView = new javax.swing.JPanel();
        jLabelWordBillView = new javax.swing.JLabel();
        jPanelCenterBillView = new javax.swing.JPanel();
        jScrollPaneBillView = new javax.swing.JScrollPane();
        jTextAreaCenterBillView = new javax.swing.JTextArea();
        jPanelVerticalLeftBillView = new javax.swing.JPanel();
        jPanelTotalBillView = new javax.swing.JPanel();
        jLabelTotalBillView = new javax.swing.JLabel();
        jPanelReceiptBillView = new javax.swing.JPanel();
        jLabelReceiptBillView = new javax.swing.JLabel();
        jPanelResetBillView = new javax.swing.JPanel();
        jLabelResetBillView = new javax.swing.JLabel();
        jLabelPROPTITBillView = new javax.swing.JLabel();
        jPanelVerticalRightBillView = new javax.swing.JPanel();
        jLabelTimeBillView = new javax.swing.JLabel();
        jLabelDateBillView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHorizontalBillView.setBackground(new java.awt.Color(255, 153, 51));

        jButtonBackBillView.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close.gif"))); // NOI18N
        jButtonBackBillView.setBorder(null);
        jButtonBackBillView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackBillViewActionPerformed(evt);
            }
        });

        jLabelNameAppBillView.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelNameAppBillView.setText(" FastFood");

        jPanelWordBillView.setBackground(new java.awt.Color(255, 153, 51));
        jPanelWordBillView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelWordBillViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelWordBillViewMousePressed(evt);
            }
        });

        jLabelWordBillView.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWordBillView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelWordBillView.setForeground(new java.awt.Color(0, 102, 255));
        jLabelWordBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cheque.gif"))); // NOI18N
        jLabelWordBillView.setText("Hóa đơn thanh toán");

        javax.swing.GroupLayout jPanelWordBillViewLayout = new javax.swing.GroupLayout(jPanelWordBillView);
        jPanelWordBillView.setLayout(jPanelWordBillViewLayout);
        jPanelWordBillViewLayout.setHorizontalGroup(
            jPanelWordBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWordBillViewLayout.createSequentialGroup()
                .addComponent(jLabelWordBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
        );
        jPanelWordBillViewLayout.setVerticalGroup(
            jPanelWordBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelWordBillView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelHorizontalBillViewLayout = new javax.swing.GroupLayout(jPanelHorizontalBillView);
        jPanelHorizontalBillView.setLayout(jPanelHorizontalBillViewLayout);
        jPanelHorizontalBillViewLayout.setHorizontalGroup(
            jPanelHorizontalBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizontalBillViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBackBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanelHorizontalBillViewLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanelWordBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHorizontalBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHorizontalBillViewLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabelNameAppBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        jPanelHorizontalBillViewLayout.setVerticalGroup(
            jPanelHorizontalBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizontalBillViewLayout.createSequentialGroup()
                .addComponent(jButtonBackBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelWordBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHorizontalBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHorizontalBillViewLayout.createSequentialGroup()
                    .addComponent(jLabelNameAppBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 67, Short.MAX_VALUE)))
        );

        jTextAreaCenterBillView.setColumns(20);
        jTextAreaCenterBillView.setRows(5);
        jScrollPaneBillView.setViewportView(jTextAreaCenterBillView);

        javax.swing.GroupLayout jPanelCenterBillViewLayout = new javax.swing.GroupLayout(jPanelCenterBillView);
        jPanelCenterBillView.setLayout(jPanelCenterBillViewLayout);
        jPanelCenterBillViewLayout.setHorizontalGroup(
            jPanelCenterBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterBillViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneBillView, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelCenterBillViewLayout.setVerticalGroup(
            jPanelCenterBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCenterBillViewLayout.createSequentialGroup()
                .addComponent(jScrollPaneBillView)
                .addContainerGap())
        );

        jPanelVerticalLeftBillView.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTotalBillView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTotalBillView.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelTotalBillView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTotalBillViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTotalBillViewMousePressed(evt);
            }
        });

        jLabelTotalBillView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelTotalBillView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTotalBillView.setForeground(new java.awt.Color(0, 0, 255));
        jLabelTotalBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-calculator.gif"))); // NOI18N
        jLabelTotalBillView.setText("Total");

        javax.swing.GroupLayout jPanelTotalBillViewLayout = new javax.swing.GroupLayout(jPanelTotalBillView);
        jPanelTotalBillView.setLayout(jPanelTotalBillViewLayout);
        jPanelTotalBillViewLayout.setHorizontalGroup(
            jPanelTotalBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTotalBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelTotalBillViewLayout.setVerticalGroup(
            jPanelTotalBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTotalBillView)
        );

        jPanelReceiptBillView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelReceiptBillViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelReceiptBillViewMousePressed(evt);
            }
        });

        jLabelReceiptBillView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelReceiptBillView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelReceiptBillView.setForeground(new java.awt.Color(0, 0, 255));
        jLabelReceiptBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-tasks.gif"))); // NOI18N
        jLabelReceiptBillView.setText("Receipt");

        javax.swing.GroupLayout jPanelReceiptBillViewLayout = new javax.swing.GroupLayout(jPanelReceiptBillView);
        jPanelReceiptBillView.setLayout(jPanelReceiptBillViewLayout);
        jPanelReceiptBillViewLayout.setHorizontalGroup(
            jPanelReceiptBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceiptBillViewLayout.createSequentialGroup()
                .addComponent(jLabelReceiptBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelReceiptBillViewLayout.setVerticalGroup(
            jPanelReceiptBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelReceiptBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelResetBillView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelResetBillViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelResetBillViewMousePressed(evt);
            }
        });

        jLabelResetBillView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelResetBillView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelResetBillView.setForeground(new java.awt.Color(0, 0, 255));
        jLabelResetBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-waste.gif"))); // NOI18N
        jLabelResetBillView.setText("Reset");

        javax.swing.GroupLayout jPanelResetBillViewLayout = new javax.swing.GroupLayout(jPanelResetBillView);
        jPanelResetBillView.setLayout(jPanelResetBillViewLayout);
        jPanelResetBillViewLayout.setHorizontalGroup(
            jPanelResetBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelResetBillView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelResetBillViewLayout.setVerticalGroup(
            jPanelResetBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelResetBillView)
        );

        jLabelPROPTITBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PROPTIT.png"))); // NOI18N

        javax.swing.GroupLayout jPanelVerticalLeftBillViewLayout = new javax.swing.GroupLayout(jPanelVerticalLeftBillView);
        jPanelVerticalLeftBillView.setLayout(jPanelVerticalLeftBillViewLayout);
        jPanelVerticalLeftBillViewLayout.setHorizontalGroup(
            jPanelVerticalLeftBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerticalLeftBillViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerticalLeftBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTotalBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelReceiptBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResetBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelVerticalLeftBillViewLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelPROPTITBillView)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelVerticalLeftBillViewLayout.setVerticalGroup(
            jPanelVerticalLeftBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerticalLeftBillViewLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelPROPTITBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelTotalBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanelReceiptBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanelResetBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jPanelVerticalRightBillView.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTimeBillView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelTimeBillView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTimeBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-alarm-clock.gif"))); // NOI18N

        jLabelDateBillView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelDateBillView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelDateBillView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-calendar.gif"))); // NOI18N

        javax.swing.GroupLayout jPanelVerticalRightBillViewLayout = new javax.swing.GroupLayout(jPanelVerticalRightBillView);
        jPanelVerticalRightBillView.setLayout(jPanelVerticalRightBillViewLayout);
        jPanelVerticalRightBillViewLayout.setHorizontalGroup(
            jPanelVerticalRightBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTimeBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelDateBillView, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        );
        jPanelVerticalRightBillViewLayout.setVerticalGroup(
            jPanelVerticalRightBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerticalRightBillViewLayout.createSequentialGroup()
                .addComponent(jLabelTimeBillView)
                .addGap(26, 26, 26)
                .addComponent(jLabelDateBillView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBillViewLayout = new javax.swing.GroupLayout(jPanelBillView);
        jPanelBillView.setLayout(jPanelBillViewLayout);
        jPanelBillViewLayout.setHorizontalGroup(
            jPanelBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanelHorizontalBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBillViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVerticalLeftBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCenterBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVerticalRightBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBillViewLayout.setVerticalGroup(
            jPanelBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillViewLayout.createSequentialGroup()
                .addComponent(jPanelHorizontalBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBillViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVerticalLeftBillView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCenterBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelVerticalRightBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBillView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBillView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackBillViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackBillViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackBillViewActionPerformed

    private void jPanelTotalBillViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTotalBillViewMouseClicked
        // TODO add your handling code here:
        InCashCartView inCash = new InCashCartView();
        //jDesktopPanelCartView.removeAll();
        //jDesktopPanelCartView.add(inCash).setVisible(true);
    }//GEN-LAST:event_jPanelTotalBillViewMouseClicked

    private void jPanelTotalBillViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTotalBillViewMousePressed
        // TODO add your handling code here:
        //jPanelTotalBillView.setBackground(clickedColorCartView);
        //jPanelReceiptBillView.setBackground(DefaultColorCartView);

        //jLabelWordCartView.setText("Thanh toán bằng tiền mặt");
        //jLabelImageCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cash.gif")));
    }//GEN-LAST:event_jPanelTotalBillViewMousePressed

    private void jPanelReceiptBillViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReceiptBillViewMouseClicked
        // TODO add your handling code here:
        QRCartView inCash = new QRCartView();
        //jDesktopPanelCartView.removeAll();
        //jDesktopPanelCartView.add(inCash).setVisible(true);
    }//GEN-LAST:event_jPanelReceiptBillViewMouseClicked

    private void jPanelReceiptBillViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelReceiptBillViewMousePressed
        // TODO add your handling code here:
        //jPanelTotalBillView.setBackground(DefaultColorCartView);
        //jPanelReceiptBillView.setBackground(clickedColorCartView);

        //jLabelWordCartView.setText("Quét mã QR");
        //jLabelImageCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-qr-code.gif")));
    }//GEN-LAST:event_jPanelReceiptBillViewMousePressed

    private void jPanelResetBillViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelResetBillViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelResetBillViewMouseClicked

    private void jPanelResetBillViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelResetBillViewMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelResetBillViewMousePressed

    private void jPanelWordBillViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelWordBillViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelWordBillViewMouseClicked

    private void jPanelWordBillViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelWordBillViewMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelWordBillViewMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackBillView;
    private javax.swing.JLabel jLabelDateBillView;
    private javax.swing.JLabel jLabelNameAppBillView;
    private javax.swing.JLabel jLabelPROPTITBillView;
    private javax.swing.JLabel jLabelReceiptBillView;
    private javax.swing.JLabel jLabelResetBillView;
    private javax.swing.JLabel jLabelTimeBillView;
    private javax.swing.JLabel jLabelTotalBillView;
    private javax.swing.JLabel jLabelWordBillView;
    private javax.swing.JPanel jPanelBillView;
    private javax.swing.JPanel jPanelCenterBillView;
    private javax.swing.JPanel jPanelHorizontalBillView;
    private javax.swing.JPanel jPanelReceiptBillView;
    private javax.swing.JPanel jPanelResetBillView;
    private javax.swing.JPanel jPanelTotalBillView;
    private javax.swing.JPanel jPanelVerticalLeftBillView;
    private javax.swing.JPanel jPanelVerticalRightBillView;
    private javax.swing.JPanel jPanelWordBillView;
    private javax.swing.JScrollPane jScrollPaneBillView;
    private javax.swing.JTextArea jTextAreaCenterBillView;
    // End of variables declaration//GEN-END:variables
}
