/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author min
 */
public class BubbleTeaView extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public BubbleTeaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBubbleTeaView = new javax.swing.JPanel();
        jButtonBackBubbleTeaException1 = new javax.swing.JButton();
        jPanelListBubbleTeaView = new javax.swing.JPanel();
        jLabelExcepiton1BubbleTeaView = new javax.swing.JLabel();
        jLabelSumBubbleTeaView = new javax.swing.JLabel();
        jLabelMoneyBubbleTeaView = new javax.swing.JLabel();
        jLabelVNDBubbleTeaView = new javax.swing.JLabel();
        jButtonAddBubbleTeaView = new javax.swing.JButton();
        jScrollPaneExcepiton1BubbleTeaView = new javax.swing.JScrollPane();
        jTableMenuOfBubbleTea = new javax.swing.JTable();
        jLabelImageBubbleTeaView = new javax.swing.JLabel();
        jButtonBackBubbleTea = new javax.swing.JButton();
        jPanelPaymentMethodsBubbleTea = new javax.swing.JPanel();
        jButtonPayWithQRCodeBubbleTeaView = new javax.swing.JButton();
        jButtonPayInCashBubbleTeaView = new javax.swing.JButton();
        jLabelPaymentMethodsBubbleTeaView = new javax.swing.JLabel();
        jPanelContainerBubbleTeaView = new javax.swing.JPanel();
        jButtonFavoriteBubbleTeaView = new javax.swing.JButton();
        jLabelPositionBubbleTeaView = new javax.swing.JLabel();
        jTextFieldNameBubbleTeaView = new javax.swing.JTextField();
        jPaneContainStarBubbleTeaView = new javax.swing.JPanel();
        jLabelStar1BubbleTeaView = new javax.swing.JLabel();
        jLabelStar2BubbleTeaView = new javax.swing.JLabel();
        jLabelStar3BubbleTeaView = new javax.swing.JLabel();
        jLabelStar4BubbleTeaView = new javax.swing.JLabel();
        jLabelStar5BubbleTeaView = new javax.swing.JLabel();
        jPanelExcepiton1BubbleTeaView = new javax.swing.JPanel();
        jLabelGreenDotBubbleTeaView = new javax.swing.JLabel();
        jLabelTimeOpenBubbleTeaView = new javax.swing.JLabel();
        jPanelHourOpenBubbleTeaView = new javax.swing.JPanel();
        jLabelHourOpenBubbleTea = new javax.swing.JLabel();
        jLabelUpToBubbleTeaView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));
        jPanelBubbleTeaView.setPreferredSize(new java.awt.Dimension(896, 678));

        jButtonBackBubbleTeaException1.setBorder(null);
        jButtonBackBubbleTeaException1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackBubbleTeaException1ActionPerformed(evt);
            }
        });

        jPanelListBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelSumBubbleTeaView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSumBubbleTeaView.setText("Tổng:");

        jLabelMoneyBubbleTeaView.setText("0");
        jLabelMoneyBubbleTeaView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVNDBubbleTeaView.setText("VNĐ");

        jButtonAddBubbleTeaView.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAddBubbleTeaView.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonAddBubbleTeaView.setText("Thêm");
        jButtonAddBubbleTeaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBubbleTeaViewActionPerformed(evt);
            }
        });

        jTableMenuOfBubbleTea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Super Sundae Trân Châu Đường Đen", "25,000",  new Integer(0)},
                {"2", "SUPER SUNDAE XOÀI", "25,000",  new Integer(0)},
                {"3", "SUPER SUNDAE SOCOLA", "25,000",  new Integer(0)},
                {"4", "SỮA KEM LẮC ĐÀO", "25,000",  new Integer(0)},
                {"5", "SUPER SUNDAE DÂU TÂY", "25,000",  new Integer(0)},
                {"6", "Hồng Trà Kem", "25,000",  new Integer(0)},
                {"7", "Sữa Kem Lắc Dâu Tây", "25,000",  new Integer(0)},
                {"8", "Super Sundae Lô Hội", "25,000",  new Integer(0)},
                {"9", "TRÀ KEM BỐN MÙA", "25,000",  new Integer(0)},
                {"10", "Dương Chi Cam Lộ", "35,000",  new Integer(0)},
                {"11", "Trà Đào Big Size", "25,000",  new Integer(0)},
                {"12", "TRÀ ĐÀO BỐN MÙA", "25,000",  new Integer(0)},
                {"13", "Nước Chanh Tươi Lạnh", "20,000",  new Integer(0)},
                {"14", "Trà Chanh Lô Hội", "20,000",  new Integer(0)},
                {"15", "Hồng Trà Mật Ong", "20,000",  new Integer(0)},
                {"16", "Hồng Trà Chanh", "22,000",  new Integer(0)},
                {"17", "Trà Đào Tứ Kỳ Xuân", "25,000",  new Integer(0)},
                {"18", "TRÀ Ô LONG BỐN MÙA", "20,000",  new Integer(0)},
                {"19", "Trà Sữa Nướng", "25,000",  new Integer(0)},
                {"20", "Trà Sữa Trân Châu Đường Đen", "25,000",  new Integer(0)},
                {"21", "Trà Sữa Trân Châu", "25,000",  new Integer(0)},
                {"22", "Trà sữa bá vương", "30,000",  new Integer(0)},
                {"23", "Trà Sữa 3Q", "25,000",  new Integer(0)},
                {"24", "Trà Sữa Thạch Dừa", "25,000",  new Integer(0)},
                {"25", "Trà Sữa 2J", "25,000",  new Integer(0)},
                {"26", "Trà Sữa Sầu Riêng", "25,000",  new Integer(0)},
                {"27", "Trà Sữa Bơ", "28,000",  new Integer(0)},
                {"28", "Trà sữa kem trứng đặc biệt", "24,000",  new Integer(0)},
                {"29", "Trà sữa phô mai tươi", "24,000",  new Integer(0)},
                {"30", "Trà sữa Hong Kong", "22,000",  new Integer(0)},
                {"31", "Trà sữa socola", "22,000",  new Integer(0)},
                {"32", "Trà sữa Lài Shan Tuyết", "22,000",  new Integer(0)},
                {"33", "Trà Sữa Kiều Mạch", "22,000",  new Integer(0)},
                {"34", "Trà sữa Cheese Ball", "24,000",  new Integer(0)},
                {"35", "Trà sữa kem trứng đặc biệt trân châu đường đen", "27,000",  new Integer(0)},
                {"36", "Trà Sữa Trân Châu Trắng", "24,000",  new Integer(0)},
                {"37", "Trà sữa khoai môn tươi", "24,000",  new Integer(0)},
                {"38", "Hồng Trà Nhật Nguyệt", "16,000",  new Integer(0)},
                {"39", "Trà Shan Tuyết Lài", "16,000",  new Integer(0)},
                {"40", "Trà Ổi Hồng", "27,000",  new Integer(0)},
                {"41", "Trà Vải Tươi", "27,000",  new Integer(0)},
                {"42", "Trà Đào Hồng", "27,000",  new Integer(0)},
                {"43", "Trà Oolong Tuyết Sơn", "16,000",  new Integer(0)},
                {"44", "Sữa tươi sương sáo thảo mộc đường đen", "27,000",  new Integer(0)},
                {"45", "Sữa tươi hoa hồng trân châu đường đen", "32,000",  new Integer(0)},
                {"46", "Sữa tươi trứng hoàng kim", "32,000",  new Integer(0)},
                {"47", "Sữa tươi cacao sữa trân châu đường đen", "32,000",  new Integer(0)},
                {"48", "Sữa tươi kem trứng đường đen", "27,000",  new Integer(0)},
                {"49", "Sữa tươi kem trứng trân châu đường đen", "32,000",  new Integer(0)},
                {"50", "Sữa tươi matcha sữa trân châu đường đen", "32,000",  new Integer(0)}
            },
            new String [] {
                "Số thứ tự", "Tên", "Giá (VNĐ)", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneExcepiton1BubbleTeaView.setViewportView(jTableMenuOfBubbleTea);
        if (jTableMenuOfBubbleTea.getColumnModel().getColumnCount() > 0) {
            jTableMenuOfBubbleTea.getColumnModel().getColumn(0).setResizable(false);
            jTableMenuOfBubbleTea.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMenuOfBubbleTea.getColumnModel().getColumn(1).setResizable(false);
            jTableMenuOfBubbleTea.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableMenuOfBubbleTea.getColumnModel().getColumn(2).setResizable(false);
            jTableMenuOfBubbleTea.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanelListBubbleTeaViewLayout = new javax.swing.GroupLayout(jPanelListBubbleTeaView);
        jPanelListBubbleTeaView.setLayout(jPanelListBubbleTeaViewLayout);
        jPanelListBubbleTeaViewLayout.setHorizontalGroup(
            jPanelListBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListBubbleTeaViewLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addGroup(jPanelListBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListBubbleTeaViewLayout.createSequentialGroup()
                        .addComponent(jLabelExcepiton1BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListBubbleTeaViewLayout.createSequentialGroup()
                        .addComponent(jButtonAddBubbleTeaView)
                        .addGap(77, 77, 77)
                        .addComponent(jLabelSumBubbleTeaView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMoneyBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelVNDBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(jPanelListBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelListBubbleTeaViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPaneExcepiton1BubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)))
        );
        jPanelListBubbleTeaViewLayout.setVerticalGroup(
            jPanelListBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListBubbleTeaViewLayout.createSequentialGroup()
                .addComponent(jLabelExcepiton1BubbleTeaView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 356, Short.MAX_VALUE)
                .addGroup(jPanelListBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMoneyBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVNDBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSumBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelListBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelListBubbleTeaViewLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addComponent(jScrollPaneExcepiton1BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        jLabelImageBubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\BubbleTeaView.png")); // NOI18N
        jLabelImageBubbleTeaView.setText("jLabel1");

        jButtonBackBubbleTea.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackBubbleTea.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-back-64.png")); // NOI18N
        jButtonBackBubbleTea.setBorder(null);
        jButtonBackBubbleTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackBubbleTeaActionPerformed(evt);
            }
        });

        jButtonPayWithQRCodeBubbleTeaView.setBackground(new java.awt.Color(51, 255, 0));
        jButtonPayWithQRCodeBubbleTeaView.setText("Quét mã QR");
        jButtonPayWithQRCodeBubbleTeaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayWithQRCodeBubbleTeaViewActionPerformed(evt);
            }
        });

        jButtonPayInCashBubbleTeaView.setBackground(new java.awt.Color(102, 255, 0));
        jButtonPayInCashBubbleTeaView.setText("Sử dụng tiền mặt");

        jLabelPaymentMethodsBubbleTeaView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPaymentMethodsBubbleTeaView.setText("      Phương thức thanh toán");

        javax.swing.GroupLayout jPanelPaymentMethodsBubbleTeaLayout = new javax.swing.GroupLayout(jPanelPaymentMethodsBubbleTea);
        jPanelPaymentMethodsBubbleTea.setLayout(jPanelPaymentMethodsBubbleTeaLayout);
        jPanelPaymentMethodsBubbleTeaLayout.setHorizontalGroup(
            jPanelPaymentMethodsBubbleTeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsBubbleTeaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPaymentMethodsBubbleTeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPaymentMethodsBubbleTeaLayout.createSequentialGroup()
                        .addComponent(jLabelPaymentMethodsBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentMethodsBubbleTeaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelPaymentMethodsBubbleTeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPayWithQRCodeBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPayInCashBubbleTeaView))
                        .addGap(28, 28, 28))))
        );
        jPanelPaymentMethodsBubbleTeaLayout.setVerticalGroup(
            jPanelPaymentMethodsBubbleTeaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsBubbleTeaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelPaymentMethodsBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPayInCashBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPayWithQRCodeBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanelContainerBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));

        jButtonFavoriteBubbleTeaView.setBackground(new java.awt.Color(255, 0, 51));
        jButtonFavoriteBubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\Favorite.png")); // NOI18N
        jButtonFavoriteBubbleTeaView.setBorder(null);
        jButtonFavoriteBubbleTeaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavoriteBubbleTeaViewActionPerformed(evt);
            }
        });

        jLabelPositionBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));
        jLabelPositionBubbleTeaView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPositionBubbleTeaView.setText("Địa điểm: ao sen ngõ số 2");

        jTextFieldNameBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));
        jTextFieldNameBubbleTeaView.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNameBubbleTeaView.setText("Tocotoco Bubble Tea - Vườn Lài");
        jTextFieldNameBubbleTeaView.setBorder(null);
        jTextFieldNameBubbleTeaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameBubbleTeaViewActionPerformed(evt);
            }
        });

        jPaneContainStarBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelStar1BubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar1BubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar2BubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar2BubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar3BubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar3BubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar4BubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar4BubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar5BubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar5BubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        javax.swing.GroupLayout jPaneContainStarBubbleTeaViewLayout = new javax.swing.GroupLayout(jPaneContainStarBubbleTeaView);
        jPaneContainStarBubbleTeaView.setLayout(jPaneContainStarBubbleTeaViewLayout);
        jPaneContainStarBubbleTeaViewLayout.setHorizontalGroup(
            jPaneContainStarBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarBubbleTeaViewLayout.createSequentialGroup()
                .addComponent(jLabelStar1BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar2BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar3BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar4BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar5BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneContainStarBubbleTeaViewLayout.setVerticalGroup(
            jPaneContainStarBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarBubbleTeaViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPaneContainStarBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneContainStarBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelStar1BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar2BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar3BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar4BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStar5BubbleTeaView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelExcepiton1BubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelGreenDotBubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelGreenDotBubbleTeaView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-green-circle-48.png")); // NOI18N

        jLabelTimeOpenBubbleTeaView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelTimeOpenBubbleTeaView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimeOpenBubbleTeaView.setText("Mở cửa 9a.m - 8p.m ");

        javax.swing.GroupLayout jPanelExcepiton1BubbleTeaViewLayout = new javax.swing.GroupLayout(jPanelExcepiton1BubbleTeaView);
        jPanelExcepiton1BubbleTeaView.setLayout(jPanelExcepiton1BubbleTeaViewLayout);
        jPanelExcepiton1BubbleTeaViewLayout.setHorizontalGroup(
            jPanelExcepiton1BubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExcepiton1BubbleTeaViewLayout.createSequentialGroup()
                .addComponent(jLabelGreenDotBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTimeOpenBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanelExcepiton1BubbleTeaViewLayout.setVerticalGroup(
            jPanelExcepiton1BubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGreenDotBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTimeOpenBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelHourOpenBubbleTeaView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelHourOpenBubbleTea.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-coins-64.png")); // NOI18N

        jLabelUpToBubbleTeaView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUpToBubbleTeaView.setText("15,000 - 35,000 VNĐ");

        javax.swing.GroupLayout jPanelHourOpenBubbleTeaViewLayout = new javax.swing.GroupLayout(jPanelHourOpenBubbleTeaView);
        jPanelHourOpenBubbleTeaView.setLayout(jPanelHourOpenBubbleTeaViewLayout);
        jPanelHourOpenBubbleTeaViewLayout.setHorizontalGroup(
            jPanelHourOpenBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHourOpenBubbleTeaViewLayout.createSequentialGroup()
                .addComponent(jLabelHourOpenBubbleTea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUpToBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelHourOpenBubbleTeaViewLayout.setVerticalGroup(
            jPanelHourOpenBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHourOpenBubbleTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUpToBubbleTeaView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelContainerBubbleTeaViewLayout = new javax.swing.GroupLayout(jPanelContainerBubbleTeaView);
        jPanelContainerBubbleTeaView.setLayout(jPanelContainerBubbleTeaViewLayout);
        jPanelContainerBubbleTeaViewLayout.setHorizontalGroup(
            jPanelContainerBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerBubbleTeaViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelContainerBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPaneContainStarBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelContainerBubbleTeaViewLayout.createSequentialGroup()
                        .addGroup(jPanelContainerBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPositionBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonFavoriteBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelHourOpenBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelExcepiton1BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNameBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelContainerBubbleTeaViewLayout.setVerticalGroup(
            jPanelContainerBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerBubbleTeaViewLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jButtonFavoriteBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTextFieldNameBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPositionBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPaneContainStarBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelExcepiton1BubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHourOpenBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBubbleTeaViewLayout = new javax.swing.GroupLayout(jPanelBubbleTeaView);
        jPanelBubbleTeaView.setLayout(jPanelBubbleTeaViewLayout);
        jPanelBubbleTeaViewLayout.setHorizontalGroup(
            jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBubbleTeaViewLayout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addGroup(jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBubbleTeaViewLayout.createSequentialGroup()
                        .addComponent(jPanelContainerBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(jButtonBackBubbleTeaException1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBackBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBubbleTeaViewLayout.createSequentialGroup()
                        .addComponent(jPanelPaymentMethodsBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBubbleTeaViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelImageBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelListBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(243, Short.MAX_VALUE)))
        );
        jPanelBubbleTeaViewLayout.setVerticalGroup(
            jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBubbleTeaViewLayout.createSequentialGroup()
                .addGroup(jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBubbleTeaViewLayout.createSequentialGroup()
                        .addComponent(jButtonBackBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBackBubbleTeaException1))
                    .addComponent(jPanelContainerBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPaymentMethodsBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(jPanelBubbleTeaViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBubbleTeaViewLayout.createSequentialGroup()
                    .addComponent(jLabelImageBubbleTeaView, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanelListBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBubbleTeaView, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddBubbleTeaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBubbleTeaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddBubbleTeaViewActionPerformed

    private void jButtonBackBubbleTeaException1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackBubbleTeaException1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackBubbleTeaException1ActionPerformed

    private void jButtonBackBubbleTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackBubbleTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackBubbleTeaActionPerformed

    private void jButtonPayWithQRCodeBubbleTeaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayWithQRCodeBubbleTeaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayWithQRCodeBubbleTeaViewActionPerformed

    private void jButtonFavoriteBubbleTeaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavoriteBubbleTeaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFavoriteBubbleTeaViewActionPerformed

    private void jTextFieldNameBubbleTeaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameBubbleTeaViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameBubbleTeaViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BubbleTeaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BubbleTeaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BubbleTeaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BubbleTeaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BubbleTeaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBubbleTeaView;
    private javax.swing.JButton jButtonBackBubbleTea;
    private javax.swing.JButton jButtonBackBubbleTeaException1;
    private javax.swing.JButton jButtonFavoriteBubbleTeaView;
    private javax.swing.JButton jButtonPayInCashBubbleTeaView;
    private javax.swing.JButton jButtonPayWithQRCodeBubbleTeaView;
    private javax.swing.JLabel jLabelExcepiton1BubbleTeaView;
    private javax.swing.JLabel jLabelGreenDotBubbleTeaView;
    private javax.swing.JLabel jLabelHourOpenBubbleTea;
    private javax.swing.JLabel jLabelImageBubbleTeaView;
    private javax.swing.JLabel jLabelMoneyBubbleTeaView;
    private javax.swing.JLabel jLabelPaymentMethodsBubbleTeaView;
    private javax.swing.JLabel jLabelPositionBubbleTeaView;
    private javax.swing.JLabel jLabelStar1BubbleTeaView;
    private javax.swing.JLabel jLabelStar2BubbleTeaView;
    private javax.swing.JLabel jLabelStar3BubbleTeaView;
    private javax.swing.JLabel jLabelStar4BubbleTeaView;
    private javax.swing.JLabel jLabelStar5BubbleTeaView;
    private javax.swing.JLabel jLabelSumBubbleTeaView;
    private javax.swing.JLabel jLabelTimeOpenBubbleTeaView;
    private javax.swing.JLabel jLabelUpToBubbleTeaView;
    private javax.swing.JLabel jLabelVNDBubbleTeaView;
    private javax.swing.JPanel jPaneContainStarBubbleTeaView;
    private javax.swing.JPanel jPanelBubbleTeaView;
    private javax.swing.JPanel jPanelContainerBubbleTeaView;
    private javax.swing.JPanel jPanelExcepiton1BubbleTeaView;
    private javax.swing.JPanel jPanelHourOpenBubbleTeaView;
    private javax.swing.JPanel jPanelListBubbleTeaView;
    private javax.swing.JPanel jPanelPaymentMethodsBubbleTea;
    private javax.swing.JScrollPane jScrollPaneExcepiton1BubbleTeaView;
    private javax.swing.JTable jTableMenuOfBubbleTea;
    private javax.swing.JTextField jTextFieldNameBubbleTeaView;
    // End of variables declaration//GEN-END:variables
}
