/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author min
 */
public class CartView extends javax.swing.JFrame {

    /**
     * Creates new form CartView
     */
    
    Color DefaultColorCartView,clickedColorCartView;
    public CartView() {
        initComponents();
        DefaultColorCartView = new Color(13,36,51);
        clickedColorCartView = new Color(255,153,51);
    
        jPanelInCashCartView.setBackground(DefaultColorCartView);
        jPanelQRCartView.setBackground(DefaultColorCartView);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCartView = new javax.swing.JPanel();
        jPanelHorizontalCartView = new javax.swing.JPanel();
        jButtonBackCartView = new javax.swing.JButton();
        jLabelWordCartView = new javax.swing.JLabel();
        jLabelNameAppCartView = new javax.swing.JLabel();
        jLabelImageCartView = new javax.swing.JLabel();
        jPanelVerticalCartView = new javax.swing.JPanel();
        jPanelInCashCartView = new javax.swing.JPanel();
        jLabelInCashCartView = new javax.swing.JLabel();
        jPanelQRCartView = new javax.swing.JPanel();
        jLabelQRCartView = new javax.swing.JLabel();
        jLabelCartImageCartView = new javax.swing.JLabel();
        jDesktopPanelCartView = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelHorizontalCartView.setBackground(new java.awt.Color(255, 153, 51));

        jButtonBackCartView.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close.gif"))); // NOI18N
        jButtonBackCartView.setBorder(null);
        jButtonBackCartView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCartViewActionPerformed(evt);
            }
        });

        jLabelWordCartView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelWordCartView.setText("Thanh toán bằng tiền mặt");

        jLabelNameAppCartView.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelNameAppCartView.setText(" FastFood App");

        jLabelImageCartView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-cash.gif")); // NOI18N

        javax.swing.GroupLayout jPanelHorizontalCartViewLayout = new javax.swing.GroupLayout(jPanelHorizontalCartView);
        jPanelHorizontalCartView.setLayout(jPanelHorizontalCartViewLayout);
        jPanelHorizontalCartViewLayout.setHorizontalGroup(
            jPanelHorizontalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizontalCartViewLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelImageCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWordCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHorizontalCartViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBackCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanelHorizontalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHorizontalCartViewLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabelNameAppCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(559, Short.MAX_VALUE)))
        );
        jPanelHorizontalCartViewLayout.setVerticalGroup(
            jPanelHorizontalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizontalCartViewLayout.createSequentialGroup()
                .addComponent(jButtonBackCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHorizontalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWordCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImageCartView))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanelHorizontalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelHorizontalCartViewLayout.createSequentialGroup()
                    .addComponent(jLabelNameAppCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );

        jPanelVerticalCartView.setBackground(new java.awt.Color(13, 36, 51));

        jPanelInCashCartView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInCashCartViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelInCashCartViewMousePressed(evt);
            }
        });

        jLabelInCashCartView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelInCashCartView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelInCashCartView.setForeground(new java.awt.Color(102, 255, 0));
        jLabelInCashCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cash.gif"))); // NOI18N
        jLabelInCashCartView.setText("Thanh toán bằng tiền mặt");

        javax.swing.GroupLayout jPanelInCashCartViewLayout = new javax.swing.GroupLayout(jPanelInCashCartView);
        jPanelInCashCartView.setLayout(jPanelInCashCartViewLayout);
        jPanelInCashCartViewLayout.setHorizontalGroup(
            jPanelInCashCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInCashCartViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelInCashCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelInCashCartViewLayout.setVerticalGroup(
            jPanelInCashCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInCashCartView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanelQRCartView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelQRCartViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelQRCartViewMousePressed(evt);
            }
        });

        jLabelQRCartView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelQRCartView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelQRCartView.setForeground(new java.awt.Color(0, 0, 255));
        jLabelQRCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-qr-code.gif"))); // NOI18N
        jLabelQRCartView.setText("  Quét mã QR");

        javax.swing.GroupLayout jPanelQRCartViewLayout = new javax.swing.GroupLayout(jPanelQRCartView);
        jPanelQRCartView.setLayout(jPanelQRCartViewLayout);
        jPanelQRCartViewLayout.setHorizontalGroup(
            jPanelQRCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQRCartViewLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(jLabelQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelQRCartViewLayout.setVerticalGroup(
            jPanelQRCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelQRCartView, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jLabelCartImageCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-shopping-cart-96.png"))); // NOI18N
        jLabelCartImageCartView.setText("jLabel3");

        javax.swing.GroupLayout jPanelVerticalCartViewLayout = new javax.swing.GroupLayout(jPanelVerticalCartView);
        jPanelVerticalCartView.setLayout(jPanelVerticalCartViewLayout);
        jPanelVerticalCartViewLayout.setHorizontalGroup(
            jPanelVerticalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerticalCartViewLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabelCartImageCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelVerticalCartViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerticalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInCashCartView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelQRCartView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelVerticalCartViewLayout.setVerticalGroup(
            jPanelVerticalCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerticalCartViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCartImageCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInCashCartView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDesktopPanelCartViewLayout = new javax.swing.GroupLayout(jDesktopPanelCartView);
        jDesktopPanelCartView.setLayout(jDesktopPanelCartViewLayout);
        jDesktopPanelCartViewLayout.setHorizontalGroup(
            jDesktopPanelCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        jDesktopPanelCartViewLayout.setVerticalGroup(
            jDesktopPanelCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCartViewLayout = new javax.swing.GroupLayout(jPanelCartView);
        jPanelCartView.setLayout(jPanelCartViewLayout);
        jPanelCartViewLayout.setHorizontalGroup(
            jPanelCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelCartViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanelHorizontalCartView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCartViewLayout.createSequentialGroup()
                        .addComponent(jPanelVerticalCartView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPanelCartView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelCartViewLayout.setVerticalGroup(
            jPanelCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCartViewLayout.createSequentialGroup()
                .addComponent(jPanelHorizontalCartView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCartViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVerticalCartView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDesktopPanelCartView)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCartView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackCartViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackCartViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackCartViewActionPerformed

    private void jPanelInCashCartViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInCashCartViewMousePressed
        // TODO add your handling code here:
        jPanelInCashCartView.setBackground(clickedColorCartView);
        jPanelQRCartView.setBackground(DefaultColorCartView);
        
        jLabelWordCartView.setText("Thanh toán bằng tiền mặt");
        jLabelImageCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-cash.gif")));
    }//GEN-LAST:event_jPanelInCashCartViewMousePressed

    private void jPanelInCashCartViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInCashCartViewMouseClicked
        // TODO add your handling code here:
        InCashCartView inCash = new InCashCartView();
        jDesktopPanelCartView.removeAll();
        jDesktopPanelCartView.add(inCash).setVisible(true);
    }//GEN-LAST:event_jPanelInCashCartViewMouseClicked

    private void jPanelQRCartViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQRCartViewMousePressed
        // TODO add your handling code here:
        jPanelInCashCartView.setBackground(DefaultColorCartView);
        jPanelQRCartView.setBackground(clickedColorCartView);

        jLabelWordCartView.setText("Quét mã QR");
        jLabelImageCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-qr-code.gif")));
    }//GEN-LAST:event_jPanelQRCartViewMousePressed

    private void jPanelQRCartViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelQRCartViewMouseClicked
        // TODO add your handling code here:
        QRCartView inCash = new QRCartView();
        jDesktopPanelCartView.removeAll();
        jDesktopPanelCartView.add(inCash).setVisible(true);
    }//GEN-LAST:event_jPanelQRCartViewMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackCartView;
    private javax.swing.JDesktopPane jDesktopPanelCartView;
    private javax.swing.JLabel jLabelCartImageCartView;
    private javax.swing.JLabel jLabelImageCartView;
    private javax.swing.JLabel jLabelInCashCartView;
    private javax.swing.JLabel jLabelNameAppCartView;
    private javax.swing.JLabel jLabelQRCartView;
    private javax.swing.JLabel jLabelWordCartView;
    private javax.swing.JPanel jPanelCartView;
    private javax.swing.JPanel jPanelHorizontalCartView;
    private javax.swing.JPanel jPanelInCashCartView;
    private javax.swing.JPanel jPanelQRCartView;
    private javax.swing.JPanel jPanelVerticalCartView;
    // End of variables declaration//GEN-END:variables
}
