/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author min
 */
public class CoffeeView extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public CoffeeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCoffeeView = new javax.swing.JPanel();
        jButtonBackCoffee = new javax.swing.JButton();
        jPanelListCoffeeView = new javax.swing.JPanel();
        jLabelException1CoffeeView = new javax.swing.JLabel();
        jLabelSumCoffeeView = new javax.swing.JLabel();
        jLabelMoneyCoffeeView = new javax.swing.JLabel();
        jLabelVNDCoffeeView = new javax.swing.JLabel();
        jButtonAddCoffeeView = new javax.swing.JButton();
        jScrollPaneException1CoffeeView = new javax.swing.JScrollPane();
        jTableMenuOfCoffee = new javax.swing.JTable();
        jLabelImageCoffeeView = new javax.swing.JLabel();
        jPanelException1CoffeeView = new javax.swing.JPanel();
        jLabelPositionCoffeeView = new javax.swing.JLabel();
        jTextFieldNameCoffeeView = new javax.swing.JTextField();
        jPanelHourOpenCoffeeView = new javax.swing.JPanel();
        jLabelHourOpenCoffee = new javax.swing.JLabel();
        jLabelUpToCoffeeView = new javax.swing.JLabel();
        jLabelTimeOpenCoffeeView = new javax.swing.JLabel();
        jPaneContainStarCoffeeView = new javax.swing.JPanel();
        jLabelStar1CoffeeView = new javax.swing.JLabel();
        jLabelStar2CoffeeView = new javax.swing.JLabel();
        jLabelStar3CoffeeView = new javax.swing.JLabel();
        jLabelStar4CoffeeView = new javax.swing.JLabel();
        jLabelStar5CoffeeView = new javax.swing.JLabel();
        jButtonFavoriteCoffeeView = new javax.swing.JButton();
        jLabelGreenDotCoffee = new javax.swing.JLabel();
        jPanelPaymentMethodsCoffeeView = new javax.swing.JPanel();
        jLabelPaymentMethodsCoffeeView = new javax.swing.JLabel();
        jButtonPayInCashCoffeeView = new javax.swing.JButton();
        jButtonPayWithQRCodeCoffeeView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelCoffeeView.setBackground(new java.awt.Color(255, 153, 51));

        jButtonBackCoffee.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackCoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-back-64.png")); // NOI18N
        jButtonBackCoffee.setBorder(null);
        jButtonBackCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackCoffeeActionPerformed(evt);
            }
        });

        jPanelListCoffeeView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelSumCoffeeView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSumCoffeeView.setText("Tổng:");

        jLabelMoneyCoffeeView.setText("0");
        jLabelMoneyCoffeeView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVNDCoffeeView.setText("VNĐ");

        jButtonAddCoffeeView.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAddCoffeeView.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonAddCoffeeView.setText("Thêm");
        jButtonAddCoffeeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCoffeeViewActionPerformed(evt);
            }
        });

        jTableMenuOfCoffee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Oreo đá xay", "35,000",  new Integer(0)},
                {"2", "Oreo cafe đá xay", "40,000",  new Integer(0)},
                {"3", "Caocao đá xay", "35,000",  new Integer(0)},
                {"4", "Matcha nóng / lạnh", "37,000",  new Integer(0)},
                {"5", "Cà phê đá xay", "35,000",  new Integer(0)},
                {"6", "Chanh tuyết", "35,000",  new Integer(0)},
                {"7", "Caocao lạnh / nóng", "32,000",  new Integer(0)},
                {"8", "Oreo cacao đá xay", "40,000",  new Integer(0)},
                {"9", "Matcha đá xay", "40,000",  new Integer(0)},
                {"10", "Cà phê sữa đá / nóng", "25,000",  new Integer(0)},
                {"11", "Cà phê đen đá / nóng", "20,000",  new Integer(0)},
                {"12", "Bạc xỉu đá / nóng", "25,000",  new Integer(0)},
                {"13", "Sữa tươi cà phê", "25,000",  new Integer(0)},
                {"14", "Cà phê yaourt", "25,000",  new Integer(0)},
                {"15", "Cafe đá", "22,000",  new Integer(0)},
                {"16", "Cafe cốt dừa", "29,000",  new Integer(0)},
                {"17", "Cà phê đen", "18,000",  new Integer(0)},
                {"18", "Cappuccino", "28,000",  new Integer(0)},
                {"19", "Espresso", "20,000",  new Integer(0)},
                {"20", "Cafe latte", "28,000",  new Integer(0)},
                {"21", "Mocha", "29,000",  new Integer(0)},
                {"22", "Spring", "28,000",  new Integer(0)},
                {"23", "Mojito passion", "36,000",  new Integer(0)},
                {"24", "Mojito lemon", "36,000",  new Integer(0)},
                {"25", "Mojito blueberry", "37,000",  new Integer(0)},
                {"26", "Blue cocalight", "30,000",  new Integer(0)},
                {"27", "Blue sky", "28,000",  new Integer(0)},
                {"28", "Chocolate chip", "34,000",  new Integer(0)},
                {"29", "Cookies", "34,000",  new Integer(0)},
                {"30", "Hazelnut", "32,000",  new Integer(0)},
                {"31", "Vanilla", "32,000",  new Integer(0)},
                {"32", "Yogurt", "25,000",  new Integer(0)},
                {"33", "Blueberry yogurt", "30,000",  new Integer(0)},
                {"34", "Strawberry yogurt", "30,000",  new Integer(0)},
                {"35", "Lipton tea", "23,000",  new Integer(0)},
                {"36", "Milk tea", "28,000",  new Integer(0)},
                {"37", "Black tea macchiato", "32,000",  new Integer(0)},
                {"38", "Matcha macchiato", "32,000",  new Integer(0)},
                {"39", "Apple mint tea", "32,000",  new Integer(0)},
                {"40", "Lychee tea", "32,000",  new Integer(0)},
                {"41", "Peach tea", "32,000",  new Integer(0)},
                {"42", "Mix berry", "37,000",  new Integer(0)},
                {"43", " Blueberry", "35,000",  new Integer(0)},
                {"44", "Strawberry", "35,000",  new Integer(0)}
            },
            new String [] {
                "Số thứ tự", "Tên", "Giá (VNĐ)", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMenuOfCoffee.setSelectionForeground(new java.awt.Color(153, 0, 153));
        jTableMenuOfCoffee.setShowGrid(true);
        jTableMenuOfCoffee.setShowHorizontalLines(true);
        jTableMenuOfCoffee.setShowVerticalLines(true);
        jScrollPaneException1CoffeeView.setViewportView(jTableMenuOfCoffee);
        if (jTableMenuOfCoffee.getColumnModel().getColumnCount() > 0) {
            jTableMenuOfCoffee.getColumnModel().getColumn(0).setResizable(false);
            jTableMenuOfCoffee.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMenuOfCoffee.getColumnModel().getColumn(1).setResizable(false);
            jTableMenuOfCoffee.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableMenuOfCoffee.getColumnModel().getColumn(2).setResizable(false);
            jTableMenuOfCoffee.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanelListCoffeeViewLayout = new javax.swing.GroupLayout(jPanelListCoffeeView);
        jPanelListCoffeeView.setLayout(jPanelListCoffeeViewLayout);
        jPanelListCoffeeViewLayout.setHorizontalGroup(
            jPanelListCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListCoffeeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListCoffeeViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelListCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListCoffeeViewLayout.createSequentialGroup()
                                .addComponent(jButtonAddCoffeeView)
                                .addGap(87, 87, 87)
                                .addComponent(jLabelSumCoffeeView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelMoneyCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelVNDCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListCoffeeViewLayout.createSequentialGroup()
                                .addComponent(jLabelException1CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))))
                    .addGroup(jPanelListCoffeeViewLayout.createSequentialGroup()
                        .addComponent(jScrollPaneException1CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelListCoffeeViewLayout.setVerticalGroup(
            jPanelListCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListCoffeeViewLayout.createSequentialGroup()
                .addComponent(jLabelException1CoffeeView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneException1CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelListCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMoneyCoffeeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelListCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSumCoffeeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelVNDCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jLabelImageCoffeeView.setBackground(new java.awt.Color(255, 153, 51));
        jLabelImageCoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\coffeeView1.png")); // NOI18N
        jLabelImageCoffeeView.setText("jLabel1");

        jPanelException1CoffeeView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelPositionCoffeeView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPositionCoffeeView.setText("Địa điểm: ao sen ngõ số 2");

        jTextFieldNameCoffeeView.setBackground(new java.awt.Color(255, 153, 51));
        jTextFieldNameCoffeeView.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNameCoffeeView.setText("Ghiền Coffee - Trà & Coffe - Thành Thái");
        jTextFieldNameCoffeeView.setBorder(null);
        jTextFieldNameCoffeeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameCoffeeViewActionPerformed(evt);
            }
        });

        jPanelHourOpenCoffeeView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelHourOpenCoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-coins-64.png")); // NOI18N

        jLabelUpToCoffeeView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUpToCoffeeView.setText("20,000 - 50,000 VNĐ");

        javax.swing.GroupLayout jPanelHourOpenCoffeeViewLayout = new javax.swing.GroupLayout(jPanelHourOpenCoffeeView);
        jPanelHourOpenCoffeeView.setLayout(jPanelHourOpenCoffeeViewLayout);
        jPanelHourOpenCoffeeViewLayout.setHorizontalGroup(
            jPanelHourOpenCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHourOpenCoffeeViewLayout.createSequentialGroup()
                .addComponent(jLabelHourOpenCoffee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUpToCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelHourOpenCoffeeViewLayout.setVerticalGroup(
            jPanelHourOpenCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHourOpenCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUpToCoffeeView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelTimeOpenCoffeeView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelTimeOpenCoffeeView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimeOpenCoffeeView.setText("Mở cửa 2p.m - 11p.m ");

        jPaneContainStarCoffeeView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelStar1CoffeeView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar1CoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar2CoffeeView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar2CoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar3CoffeeView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar3CoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar4CoffeeView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar4CoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar5CoffeeView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar5CoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        javax.swing.GroupLayout jPaneContainStarCoffeeViewLayout = new javax.swing.GroupLayout(jPaneContainStarCoffeeView);
        jPaneContainStarCoffeeView.setLayout(jPaneContainStarCoffeeViewLayout);
        jPaneContainStarCoffeeViewLayout.setHorizontalGroup(
            jPaneContainStarCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarCoffeeViewLayout.createSequentialGroup()
                .addComponent(jLabelStar1CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar2CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar3CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar4CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar5CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPaneContainStarCoffeeViewLayout.setVerticalGroup(
            jPaneContainStarCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarCoffeeViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPaneContainStarCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneContainStarCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelStar1CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar2CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar3CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar4CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStar5CoffeeView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonFavoriteCoffeeView.setBackground(new java.awt.Color(255, 0, 51));
        jButtonFavoriteCoffeeView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\Favorite.png")); // NOI18N
        jButtonFavoriteCoffeeView.setBorder(null);
        jButtonFavoriteCoffeeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavoriteCoffeeViewActionPerformed(evt);
            }
        });

        jLabelGreenDotCoffee.setBackground(new java.awt.Color(255, 102, 0));
        jLabelGreenDotCoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-green-circle-48.png")); // NOI18N

        javax.swing.GroupLayout jPanelException1CoffeeViewLayout = new javax.swing.GroupLayout(jPanelException1CoffeeView);
        jPanelException1CoffeeView.setLayout(jPanelException1CoffeeViewLayout);
        jPanelException1CoffeeViewLayout.setHorizontalGroup(
            jPanelException1CoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelException1CoffeeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelException1CoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPositionCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFavoriteCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHourOpenCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelException1CoffeeViewLayout.createSequentialGroup()
                        .addComponent(jLabelGreenDotCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTimeOpenCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPaneContainStarCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanelException1CoffeeViewLayout.setVerticalGroup(
            jPanelException1CoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelException1CoffeeViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFavoriteCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNameCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelPositionCoffeeView)
                .addGap(4, 4, 4)
                .addComponent(jPaneContainStarCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelException1CoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTimeOpenCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGreenDotCoffee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHourOpenCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelPaymentMethodsCoffeeView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPaymentMethodsCoffeeView.setText("      Phương thức thanh toán");

        jButtonPayInCashCoffeeView.setBackground(new java.awt.Color(102, 255, 0));
        jButtonPayInCashCoffeeView.setText("Sử dụng tiền mặt");

        jButtonPayWithQRCodeCoffeeView.setBackground(new java.awt.Color(51, 255, 0));
        jButtonPayWithQRCodeCoffeeView.setText("Quét mã QR");
        jButtonPayWithQRCodeCoffeeView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayWithQRCodeCoffeeViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaymentMethodsCoffeeViewLayout = new javax.swing.GroupLayout(jPanelPaymentMethodsCoffeeView);
        jPanelPaymentMethodsCoffeeView.setLayout(jPanelPaymentMethodsCoffeeViewLayout);
        jPanelPaymentMethodsCoffeeViewLayout.setHorizontalGroup(
            jPanelPaymentMethodsCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsCoffeeViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaymentMethodsCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentMethodsCoffeeViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPaymentMethodsCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPayInCashCoffeeView, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPayWithQRCodeCoffeeView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanelPaymentMethodsCoffeeViewLayout.setVerticalGroup(
            jPanelPaymentMethodsCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsCoffeeViewLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelPaymentMethodsCoffeeView, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPayInCashCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPayWithQRCodeCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanelCoffeeViewLayout = new javax.swing.GroupLayout(jPanelCoffeeView);
        jPanelCoffeeView.setLayout(jPanelCoffeeViewLayout);
        jPanelCoffeeViewLayout.setHorizontalGroup(
            jPanelCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                .addComponent(jPanelListCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanelPaymentMethodsCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCoffeeViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonBackCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelImageCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(jPanelException1CoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(108, Short.MAX_VALUE)))
        );
        jPanelCoffeeViewLayout.setVerticalGroup(
            jPanelCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                .addGroup(jPanelCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelListCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                        .addComponent(jButtonBackCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(jPanelPaymentMethodsCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                    .addGroup(jPanelCoffeeViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelException1CoffeeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCoffeeViewLayout.createSequentialGroup()
                            .addComponent(jLabelImageCoffeeView, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(408, 408, 408)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCoffeeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCoffeeView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddCoffeeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCoffeeViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddCoffeeViewActionPerformed

    private void jTextFieldNameCoffeeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameCoffeeViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameCoffeeViewActionPerformed

    private void jButtonFavoriteCoffeeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavoriteCoffeeViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFavoriteCoffeeViewActionPerformed

    private void jButtonPayWithQRCodeCoffeeViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayWithQRCodeCoffeeViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayWithQRCodeCoffeeViewActionPerformed

    private void jButtonBackCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackCoffeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoffeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoffeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoffeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoffeeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoffeeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCoffeeView;
    private javax.swing.JButton jButtonBackCoffee;
    private javax.swing.JButton jButtonFavoriteCoffeeView;
    private javax.swing.JButton jButtonPayInCashCoffeeView;
    private javax.swing.JButton jButtonPayWithQRCodeCoffeeView;
    private javax.swing.JLabel jLabelException1CoffeeView;
    private javax.swing.JLabel jLabelGreenDotCoffee;
    private javax.swing.JLabel jLabelHourOpenCoffee;
    private javax.swing.JLabel jLabelImageCoffeeView;
    private javax.swing.JLabel jLabelMoneyCoffeeView;
    private javax.swing.JLabel jLabelPaymentMethodsCoffeeView;
    private javax.swing.JLabel jLabelPositionCoffeeView;
    private javax.swing.JLabel jLabelStar1CoffeeView;
    private javax.swing.JLabel jLabelStar2CoffeeView;
    private javax.swing.JLabel jLabelStar3CoffeeView;
    private javax.swing.JLabel jLabelStar4CoffeeView;
    private javax.swing.JLabel jLabelStar5CoffeeView;
    private javax.swing.JLabel jLabelSumCoffeeView;
    private javax.swing.JLabel jLabelTimeOpenCoffeeView;
    private javax.swing.JLabel jLabelUpToCoffeeView;
    private javax.swing.JLabel jLabelVNDCoffeeView;
    private javax.swing.JPanel jPaneContainStarCoffeeView;
    private javax.swing.JPanel jPanelCoffeeView;
    private javax.swing.JPanel jPanelException1CoffeeView;
    private javax.swing.JPanel jPanelHourOpenCoffeeView;
    private javax.swing.JPanel jPanelListCoffeeView;
    private javax.swing.JPanel jPanelPaymentMethodsCoffeeView;
    private javax.swing.JScrollPane jScrollPaneException1CoffeeView;
    private javax.swing.JTable jTableMenuOfCoffee;
    private javax.swing.JTextField jTextFieldNameCoffeeView;
    // End of variables declaration//GEN-END:variables
}
