package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author min
 */
public class KFCView extends javax.swing.JFrame {

    /**
     * Creates new form KFCView
     */
    public KFCView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKFCView = new javax.swing.JPanel();
        jPanelListKFCView = new javax.swing.JPanel();
        jScrollPaneException1KFCView = new javax.swing.JScrollPane();
        jTableMenuOfKFC = new javax.swing.JTable();
        jLabelException1KFCView = new javax.swing.JLabel();
        jLabelSumKFCView = new javax.swing.JLabel();
        jLabelMoneyKFCView = new javax.swing.JLabel();
        jLabelVNDKFCView = new javax.swing.JLabel();
        jButtonAddKFCView = new javax.swing.JButton();
        jButtonBackKFC = new javax.swing.JButton();
        jLabelImageKFCView = new javax.swing.JLabel();
        jPanelPaymentMethodsKFCView = new javax.swing.JPanel();
        jLabelPaymentMethodsKFCView = new javax.swing.JLabel();
        jButtonPayInCashKFCView = new javax.swing.JButton();
        jButtonPayWithQRCodeKFCView = new javax.swing.JButton();
        jPanelException1KFCView = new javax.swing.JPanel();
        jLabelPositionKFCView = new javax.swing.JLabel();
        jTextFieldNameKFCView = new javax.swing.JTextField();
        jPanelHourOpenKFCView = new javax.swing.JPanel();
        jLabelHourOpenKFC = new javax.swing.JLabel();
        jLabelUpToKFCView = new javax.swing.JLabel();
        jLabelTimeOpenKFCView = new javax.swing.JLabel();
        jPaneContainStarKFCView = new javax.swing.JPanel();
        jLabelStar1KFCView = new javax.swing.JLabel();
        jLabelStar2KFCView = new javax.swing.JLabel();
        jLabelStar3KFCView = new javax.swing.JLabel();
        jLabelStar4KFCView = new javax.swing.JLabel();
        jLabelStar5KFCView = new javax.swing.JLabel();
        jButtonFavoriteKFCView = new javax.swing.JButton();
        jLabelGreenDotKFC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelKFCView.setBackground(new java.awt.Color(255, 153, 51));

        jPanelListKFCView.setBackground(new java.awt.Color(255, 153, 51));

        jTableMenuOfKFC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1 Cơm Phi-lê Gà Quay/Cơm Phi-lê Gà Quay Tiêu + 1 Lon Pepsi", "45,000",  new Integer(0)},
                {"2", "Combo Cơm Trưa Gà Rán", "45,000",  new Integer(0)},
                {"3", "Combo Cơm Gà Xốt Teriyaki", "45,000",  new Integer(0)},
                {"4", "Gà rán (3 miếng)", "105,000",  new Integer(0)},
                {"5", "Gà rán (2 miếng)", "71,000",  new Integer(0)},
                {"6", "Gà rán (1 miếng)", "36,000",  new Integer(0)},
                {"7", "Gà Quay (1 Miếng)", "75,000",  new Integer(0)},
                {"8", "Gà Hot Wings (5 miếng)", "85,000",  new Integer(0)},
                {"9", "Gà Hot Wings (3 miếng)", "55,000",  new Integer(0)},
                {"10", "Combo Cơm Trưa Phi-lê Gà Quay", "45,000",  new Integer(0)},
                {"11", "Combo Cơm Trưa Gà Rán", "45,000",  new Integer(0)},
                {"12", "Combo Cơm Gà Xốt Teriyaki", "45,000",  new Integer(0)},
                {"13", "Combo Trưa Burger Tôm", "45,000",  new Integer(0)},
                {"14", "Combo Trưa Mì Ý Gà Viên", "45,000",  new Integer(0)},
                {"15", "Combo Cơm Trưa Gà Bít-Tết", "45,000",  new Integer(0)},
                {"16", "Combo Cơm Trưa Gà Xiên Que", "45,000",  new Integer(0)},
                {"17", "Cơm Gà Rán", "46,000",  new Integer(0)},
                {"18", "Gà Miếng Nuggets", "27,000",  new Integer(0)},
                {"19", "2 Miếng Gà + 1 Bánh Trứng + 1 Lon Pepsi", "99,000",  new Integer(0)},
                {"20", "1 Miếng Gà + 1 Hộp Gà Viên (Vừa) + 1 Lon Pepsi ", "89,000",  new Integer(0)},
                {"21", "1 Burger Tôm + 1 Miếng Gà + 1 Lon Pepsi", "91,000",  new Integer(0)},
                {"22", "5 Miếng Gà + 1 Hộp Gà Viên (Vừa) + 3 Lon Pepsi", "259,000",  new Integer(0)},
                {"23", "4 Miếng Gà + 3 Nuggets + 2 Lon Pepsi", "189,000",  new Integer(0)},
                {"24", "1 Miếng Gà Quay Giấy Bạc + 1 Salad Hạt", "109,000",  new Integer(0)}
            },
            new String [] {
                "Số thứ tự", "Tên", "Giá (VNĐ)", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneException1KFCView.setViewportView(jTableMenuOfKFC);
        if (jTableMenuOfKFC.getColumnModel().getColumnCount() > 0) {
            jTableMenuOfKFC.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableMenuOfKFC.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        jLabelSumKFCView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelSumKFCView.setText("Tổng:");

        jLabelMoneyKFCView.setText("0");
        jLabelMoneyKFCView.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelVNDKFCView.setText("VNĐ");

        jButtonAddKFCView.setBackground(new java.awt.Color(255, 255, 0));
        jButtonAddKFCView.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButtonAddKFCView.setText("Thêm");
        jButtonAddKFCView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddKFCViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListKFCViewLayout = new javax.swing.GroupLayout(jPanelListKFCView);
        jPanelListKFCView.setLayout(jPanelListKFCViewLayout);
        jPanelListKFCViewLayout.setHorizontalGroup(
            jPanelListKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListKFCViewLayout.createSequentialGroup()
                .addGroup(jPanelListKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelListKFCViewLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelException1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanelListKFCViewLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButtonAddKFCView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSumKFCView)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelMoneyKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabelVNDKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanelListKFCViewLayout.createSequentialGroup()
                .addComponent(jScrollPaneException1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelListKFCViewLayout.setVerticalGroup(
            jPanelListKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListKFCViewLayout.createSequentialGroup()
                .addComponent(jScrollPaneException1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelException1KFCView)
                .addGap(18, 18, 18)
                .addGroup(jPanelListKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelMoneyKFCView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelSumKFCView, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(jLabelVNDKFCView, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                    .addComponent(jButtonAddKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jButtonBackKFC.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackKFC.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-back-64.png")); // NOI18N
        jButtonBackKFC.setBorder(null);

        jLabelImageKFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\KFCView.png")); // NOI18N
        jLabelImageKFCView.setText("jLabel1");

        jLabelPaymentMethodsKFCView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPaymentMethodsKFCView.setText("      Phương thức thanh toán");

        jButtonPayInCashKFCView.setBackground(new java.awt.Color(102, 255, 0));
        jButtonPayInCashKFCView.setText("Sử dụng tiền mặt");

        jButtonPayWithQRCodeKFCView.setBackground(new java.awt.Color(51, 255, 0));
        jButtonPayWithQRCodeKFCView.setText("Quét mã QR");
        jButtonPayWithQRCodeKFCView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayWithQRCodeKFCViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaymentMethodsKFCViewLayout = new javax.swing.GroupLayout(jPanelPaymentMethodsKFCView);
        jPanelPaymentMethodsKFCView.setLayout(jPanelPaymentMethodsKFCViewLayout);
        jPanelPaymentMethodsKFCViewLayout.setHorizontalGroup(
            jPanelPaymentMethodsKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsKFCViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPaymentMethodsKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentMethodsKFCViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPaymentMethodsKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPayInCashKFCView, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPayWithQRCodeKFCView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanelPaymentMethodsKFCViewLayout.setVerticalGroup(
            jPanelPaymentMethodsKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentMethodsKFCViewLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelPaymentMethodsKFCView, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPayInCashKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPayWithQRCodeKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanelException1KFCView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelPositionKFCView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPositionKFCView.setText("Địa điểm: ao sen ngõ số 0");

        jTextFieldNameKFCView.setBackground(new java.awt.Color(255, 153, 51));
        jTextFieldNameKFCView.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNameKFCView.setText("Gà Rán KFC - Âu Cơ");
        jTextFieldNameKFCView.setBorder(null);
        jTextFieldNameKFCView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameKFCViewActionPerformed(evt);
            }
        });

        jPanelHourOpenKFCView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelHourOpenKFC.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-coins-64.png")); // NOI18N

        jLabelUpToKFCView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUpToKFCView.setText("35,000 - 260,000 VNĐ");

        javax.swing.GroupLayout jPanelHourOpenKFCViewLayout = new javax.swing.GroupLayout(jPanelHourOpenKFCView);
        jPanelHourOpenKFCView.setLayout(jPanelHourOpenKFCViewLayout);
        jPanelHourOpenKFCViewLayout.setHorizontalGroup(
            jPanelHourOpenKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHourOpenKFCViewLayout.createSequentialGroup()
                .addComponent(jLabelHourOpenKFC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelUpToKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanelHourOpenKFCViewLayout.setVerticalGroup(
            jPanelHourOpenKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHourOpenKFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelUpToKFCView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelTimeOpenKFCView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelTimeOpenKFCView.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTimeOpenKFCView.setText("Mở cửa 10a.m - 11p.m ");

        jPaneContainStarKFCView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelStar1KFCView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar1KFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar2KFCView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar2KFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar3KFCView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar3KFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar4KFCView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar4KFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        jLabelStar5KFCView.setBackground(new java.awt.Color(255, 102, 0));
        jLabelStar5KFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-star-48.png")); // NOI18N

        javax.swing.GroupLayout jPaneContainStarKFCViewLayout = new javax.swing.GroupLayout(jPaneContainStarKFCView);
        jPaneContainStarKFCView.setLayout(jPaneContainStarKFCViewLayout);
        jPaneContainStarKFCViewLayout.setHorizontalGroup(
            jPaneContainStarKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarKFCViewLayout.createSequentialGroup()
                .addComponent(jLabelStar1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar2KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar3KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar4KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStar5KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPaneContainStarKFCViewLayout.setVerticalGroup(
            jPaneContainStarKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneContainStarKFCViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPaneContainStarKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneContainStarKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelStar1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar2KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar3KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelStar4KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStar5KFCView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButtonFavoriteKFCView.setBackground(new java.awt.Color(255, 0, 51));
        jButtonFavoriteKFCView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\Favorite.png")); // NOI18N
        jButtonFavoriteKFCView.setBorder(null);
        jButtonFavoriteKFCView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavoriteKFCViewActionPerformed(evt);
            }
        });

        jLabelGreenDotKFC.setBackground(new java.awt.Color(255, 102, 0));
        jLabelGreenDotKFC.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Documents\\NetBeansProjects\\tester\\src\\Image\\icons8-green-circle-48.png")); // NOI18N

        javax.swing.GroupLayout jPanelException1KFCViewLayout = new javax.swing.GroupLayout(jPanelException1KFCView);
        jPanelException1KFCView.setLayout(jPanelException1KFCViewLayout);
        jPanelException1KFCViewLayout.setHorizontalGroup(
            jPanelException1KFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelException1KFCViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelException1KFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPositionKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFavoriteKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelHourOpenKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelException1KFCViewLayout.createSequentialGroup()
                        .addComponent(jLabelGreenDotKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelTimeOpenKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPaneContainStarKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanelException1KFCViewLayout.setVerticalGroup(
            jPanelException1KFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelException1KFCViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFavoriteKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldNameKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabelPositionKFCView)
                .addGap(4, 4, 4)
                .addComponent(jPaneContainStarKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelException1KFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTimeOpenKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGreenDotKFC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHourOpenKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelKFCViewLayout = new javax.swing.GroupLayout(jPanelKFCView);
        jPanelKFCView.setLayout(jPanelKFCViewLayout);
        jPanelKFCViewLayout.setHorizontalGroup(
            jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addGroup(jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKFCViewLayout.createSequentialGroup()
                        .addComponent(jPanelPaymentMethodsKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKFCViewLayout.createSequentialGroup()
                        .addComponent(jPanelException1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                            .addComponent(jPanelListKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(255, Short.MAX_VALUE))
                        .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                            .addComponent(jLabelImageKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                            .addComponent(jButtonBackKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanelKFCViewLayout.setVerticalGroup(
            jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelException1KFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanelPaymentMethodsKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                    .addGroup(jPanelKFCViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelKFCViewLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabelImageKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonBackKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelListKFCView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelKFCView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelKFCView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddKFCViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddKFCViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddKFCViewActionPerformed

    private void jButtonPayWithQRCodeKFCViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayWithQRCodeKFCViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPayWithQRCodeKFCViewActionPerformed

    private void jTextFieldNameKFCViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameKFCViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameKFCViewActionPerformed

    private void jButtonFavoriteKFCViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavoriteKFCViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFavoriteKFCViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KFCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KFCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KFCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KFCView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KFCView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddKFCView;
    private javax.swing.JButton jButtonBackKFC;
    private javax.swing.JButton jButtonFavoriteKFCView;
    private javax.swing.JButton jButtonPayInCashKFCView;
    private javax.swing.JButton jButtonPayWithQRCodeKFCView;
    private javax.swing.JLabel jLabelException1KFCView;
    private javax.swing.JLabel jLabelGreenDotKFC;
    private javax.swing.JLabel jLabelHourOpenKFC;
    private javax.swing.JLabel jLabelImageKFCView;
    private javax.swing.JLabel jLabelMoneyKFCView;
    private javax.swing.JLabel jLabelPaymentMethodsKFCView;
    private javax.swing.JLabel jLabelPositionKFCView;
    private javax.swing.JLabel jLabelStar1KFCView;
    private javax.swing.JLabel jLabelStar2KFCView;
    private javax.swing.JLabel jLabelStar3KFCView;
    private javax.swing.JLabel jLabelStar4KFCView;
    private javax.swing.JLabel jLabelStar5KFCView;
    private javax.swing.JLabel jLabelSumKFCView;
    private javax.swing.JLabel jLabelTimeOpenKFCView;
    private javax.swing.JLabel jLabelUpToKFCView;
    private javax.swing.JLabel jLabelVNDKFCView;
    private javax.swing.JPanel jPaneContainStarKFCView;
    private javax.swing.JPanel jPanelException1KFCView;
    private javax.swing.JPanel jPanelHourOpenKFCView;
    private javax.swing.JPanel jPanelKFCView;
    private javax.swing.JPanel jPanelListKFCView;
    private javax.swing.JPanel jPanelPaymentMethodsKFCView;
    private javax.swing.JScrollPane jScrollPaneException1KFCView;
    private javax.swing.JTable jTableMenuOfKFC;
    private javax.swing.JTextField jTextFieldNameKFCView;
    // End of variables declaration//GEN-END:variables
}
