package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author min
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMainView = new javax.swing.JPanel();
        jLabelDelivery = new javax.swing.JLabel();
        jLabelException1MainView = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jTextFieldPosition = new javax.swing.JTextField();
        jLabelHeader = new javax.swing.JLabel();
        jPanelMainBody = new javax.swing.JPanel();
        jButtonHamburger = new javax.swing.JButton();
        jButtonDealHotToday = new javax.swing.JButton();
        jButtonCart = new javax.swing.JButton();
        jButtonDiscountCode = new javax.swing.JButton();
        jButtonHotdog = new javax.swing.JButton();
        jButtonCollection = new javax.swing.JButton();
        jButtonFreeshipXtra = new javax.swing.JButton();
        jButtonCoffee = new javax.swing.JButton();
        jButtonBubbleTea = new javax.swing.JButton();
        jButtonCategory = new javax.swing.JButton();
        jButtonBeer = new javax.swing.JButton();
        jButtonPizza = new javax.swing.JButton();
        jButtonKFC = new javax.swing.JButton();
        jButtonBread = new javax.swing.JButton();
        jLabelHamburger = new javax.swing.JLabel();
        jLabelDealHotToday = new javax.swing.JLabel();
        jLabelCart = new javax.swing.JLabel();
        jLabelDiscountCode = new javax.swing.JLabel();
        jLabelHotdog = new javax.swing.JLabel();
        jLabelCollection = new javax.swing.JLabel();
        jLabelFreeshipXtra = new javax.swing.JLabel();
        jLabelCoffee = new javax.swing.JLabel();
        jLabelBubbleTea = new javax.swing.JLabel();
        jLabelrBread = new javax.swing.JLabel();
        jLabelKFC = new javax.swing.JLabel();
        jLabelPizza = new javax.swing.JLabel();
        jLabelBeer = new javax.swing.JLabel();
        jLabelCategory = new javax.swing.JLabel();
        jPanelFooter = new javax.swing.JPanel();
        jButtonHomePage = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonFavorite = new javax.swing.JButton();
        jButtonNotification = new javax.swing.JButton();
        jButtonMe = new javax.swing.JButton();
        jLabelOut = new javax.swing.JLabel();
        jLabelOrder = new javax.swing.JLabel();
        jLabelFavorite = new javax.swing.JLabel();
        jLabelNotification = new javax.swing.JLabel();
        jLabelMe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelMainView.setBackground(new java.awt.Color(255, 255, 255));

        jLabelDelivery.setText("Giao tới:");

        jLabelPosition.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-location-48.png")); // NOI18N

        jLabelHeader.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\R.png")); // NOI18N

        jPanelMainBody.setBackground(new java.awt.Color(255, 255, 255));

        jButtonHamburger.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-hamburger-48.png")); // NOI18N
        jButtonHamburger.setText("HamburgerButton");
        jButtonHamburger.setBorder(null);
        jButtonHamburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHamburgerActionPerformed(evt);
            }
        });

        jButtonDealHotToday.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-hot-sale-64.png")); // NOI18N
        jButtonDealHotToday.setBorder(null);
        jButtonDealHotToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDealHotTodayActionPerformed(evt);
            }
        });

        jButtonCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-shopping-cart-64.png")); // NOI18N
        jButtonCart.setBorder(null);
        jButtonCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCartActionPerformed(evt);
            }
        });

        jButtonDiscountCode.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-discount-48.png")); // NOI18N
        jButtonDiscountCode.setBorder(null);
        jButtonDiscountCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiscountCodeActionPerformed(evt);
            }
        });

        jButtonHotdog.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-hot-dog-48.png")); // NOI18N
        jButtonHotdog.setBorder(null);
        jButtonHotdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHotdogActionPerformed(evt);
            }
        });

        jButtonCollection.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-food-bar-48.png")); // NOI18N
        jButtonCollection.setBorder(null);
        jButtonCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCollectionActionPerformed(evt);
            }
        });

        jButtonFreeshipXtra.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-ecommerce-64.png")); // NOI18N
        jButtonFreeshipXtra.setBorder(null);
        jButtonFreeshipXtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFreeshipXtraActionPerformed(evt);
            }
        });

        jButtonCoffee.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-iced-coffee-40.png")); // NOI18N
        jButtonCoffee.setBorder(null);
        jButtonCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoffeeActionPerformed(evt);
            }
        });

        jButtonBubbleTea.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-bubble-tea-40.png")); // NOI18N
        jButtonBubbleTea.setBorder(null);
        jButtonBubbleTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBubbleTeaActionPerformed(evt);
            }
        });

        jButtonCategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-category-64.png")); // NOI18N
        jButtonCategory.setBorder(null);
        jButtonCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoryActionPerformed(evt);
            }
        });

        jButtonBeer.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-pint-48.png")); // NOI18N
        jButtonBeer.setBorder(null);
        jButtonBeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBeerActionPerformed(evt);
            }
        });

        jButtonPizza.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-pizza-48.png")); // NOI18N
        jButtonPizza.setBorder(null);
        jButtonPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPizzaActionPerformed(evt);
            }
        });

        jButtonKFC.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-kfc-chicken-48.png")); // NOI18N
        jButtonKFC.setBorder(null);
        jButtonKFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKFCActionPerformed(evt);
            }
        });

        jButtonBread.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-bread-64.png")); // NOI18N
        jButtonBread.setBorder(null);
        jButtonBread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBreadActionPerformed(evt);
            }
        });

        jLabelHamburger.setText("    Hamburger");

        jLabelDealHotToday.setText("Deal hot hôm nay");

        jLabelCart.setText("Giỏ hàng");

        jLabelDiscountCode.setText("Mã giảm giá");

        jLabelHotdog.setText("   Hot dog");

        jLabelCollection.setText(" Bộ sưu tập");

        jLabelFreeshipXtra.setText("Freeship Xtra");

        jLabelCoffee.setText("  Coffee");

        jLabelBubbleTea.setText("   Trà sữa");

        jLabelrBread.setText("Bánh mì");

        jLabelKFC.setText("Gà rán KFC");

        jLabelPizza.setText("Pizza");

        jLabelBeer.setText("  Bia hơi");

        jLabelCategory.setText("Danh mục");

        javax.swing.GroupLayout jPanelMainBodyLayout = new javax.swing.GroupLayout(jPanelMainBody);
        jPanelMainBody.setLayout(jPanelMainBodyLayout);
        jPanelMainBodyLayout.setHorizontalGroup(
            jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonHamburger, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHamburger)
                            .addComponent(jButtonCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabelCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainBodyLayout.createSequentialGroup()
                                .addComponent(jButtonDealHotToday, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainBodyLayout.createSequentialGroup()
                                .addComponent(jLabelDealHotToday)
                                .addGap(29, 29, 29)))
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelCart))))
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelrBread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonBread, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelHotdog, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                            .addComponent(jButtonHotdog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKFC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPizza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainBodyLayout.createSequentialGroup()
                                .addComponent(jLabelPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCollection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCollection, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFreeshipXtra, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFreeshipXtra)
                    .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanelMainBodyLayout.setVerticalGroup(
            jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFreeshipXtra, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDiscountCode, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonDealHotToday, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonCart, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHotdog, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonHamburger, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelFreeshipXtra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelHotdog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelCart, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                    .addComponent(jLabelDiscountCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelDealHotToday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelHamburger, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonKFC, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelMainBodyLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabelCollection, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBubbleTea, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBread, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBeer, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jLabelBubbleTea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelrBread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelKFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBeer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelFooter.setForeground(new java.awt.Color(255, 102, 0));

        jButtonHomePage.setForeground(new java.awt.Color(255, 102, 0));
        jButtonHomePage.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-home-page-60.png")); // NOI18N
        jButtonHomePage.setBorder(null);
        jButtonHomePage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomePageActionPerformed(evt);
            }
        });

        jButtonOrder.setForeground(new java.awt.Color(255, 102, 0));
        jButtonOrder.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-purchase-order-60.png")); // NOI18N
        jButtonOrder.setBorder(null);
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonFavorite.setForeground(new java.awt.Color(255, 102, 0));
        jButtonFavorite.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-favorite-48.png")); // NOI18N
        jButtonFavorite.setBorder(null);
        jButtonFavorite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFavoriteActionPerformed(evt);
            }
        });

        jButtonNotification.setForeground(new java.awt.Color(255, 102, 0));
        jButtonNotification.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-alarm-50.png")); // NOI18N
        jButtonNotification.setBorder(null);
        jButtonNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNotificationActionPerformed(evt);
            }
        });

        jButtonMe.setForeground(new java.awt.Color(255, 102, 0));
        jButtonMe.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Downloads\\icons8-me-58.png")); // NOI18N
        jButtonMe.setBorder(null);
        jButtonMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeActionPerformed(evt);
            }
        });

        jLabelOut.setText("Đăng xuất");

        jLabelOrder.setText("Đơn hàng");

        jLabelFavorite.setText(" Đã thích");

        jLabelNotification.setText("Thông báo");

        jLabelMe.setText("   Tôi");

        javax.swing.GroupLayout jPanelFooterLayout = new javax.swing.GroupLayout(jPanelFooter);
        jPanelFooter.setLayout(jPanelFooterLayout);
        jPanelFooterLayout.setHorizontalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addComponent(jButtonHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabelOut)
                        .addGap(60, 60, 60)
                        .addComponent(jLabelOrder)))
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButtonFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFooterLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)))
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNotification, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonMe, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFooterLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabelMe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelFooterLayout.setVerticalGroup(
            jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonOrder, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonFavorite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNotification, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOut)
                    .addComponent(jLabelOrder)
                    .addComponent(jLabelFavorite)
                    .addComponent(jLabelNotification)
                    .addComponent(jLabelMe))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainViewLayout = new javax.swing.GroupLayout(jPanelMainView);
        jPanelMainView.setLayout(jPanelMainViewLayout);
        jPanelMainViewLayout.setHorizontalGroup(
            jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainViewLayout.createSequentialGroup()
                .addComponent(jLabelDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainViewLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelException1MainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMainViewLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldPosition)
                        .addContainerGap())))
            .addGroup(jPanelMainViewLayout.createSequentialGroup()
                .addGroup(jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanelFooter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMainViewLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jPanelMainBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)))
                    .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMainViewLayout.setVerticalGroup(
            jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainViewLayout.createSequentialGroup()
                .addComponent(jLabelException1MainView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosition)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMainBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMainView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMainView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHamburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHamburgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHamburgerActionPerformed

    private void jButtonFreeshipXtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFreeshipXtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFreeshipXtraActionPerformed

    private void jButtonCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCoffeeActionPerformed

    private void jButtonBubbleTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBubbleTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBubbleTeaActionPerformed

    private void jButtonNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNotificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNotificationActionPerformed

    private void jButtonHomePageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomePageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHomePageActionPerformed

    private void jButtonFavoriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFavoriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFavoriteActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jButtonDealHotTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDealHotTodayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDealHotTodayActionPerformed

    private void jButtonCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCartActionPerformed

    private void jButtonDiscountCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiscountCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDiscountCodeActionPerformed

    private void jButtonHotdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHotdogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHotdogActionPerformed

    private void jButtonCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCollectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCollectionActionPerformed

    private void jButtonBreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBreadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBreadActionPerformed

    private void jButtonKFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKFCActionPerformed

    private void jButtonPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPizzaActionPerformed

    private void jButtonBeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBeerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBeerActionPerformed

    private void jButtonCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCategoryActionPerformed

    private void jButtonMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBeer;
    private javax.swing.JButton jButtonBread;
    private javax.swing.JButton jButtonBubbleTea;
    private javax.swing.JButton jButtonCart;
    private javax.swing.JButton jButtonCategory;
    private javax.swing.JButton jButtonCoffee;
    private javax.swing.JButton jButtonCollection;
    private javax.swing.JButton jButtonDealHotToday;
    private javax.swing.JButton jButtonDiscountCode;
    private javax.swing.JButton jButtonFavorite;
    private javax.swing.JButton jButtonFreeshipXtra;
    private javax.swing.JButton jButtonHamburger;
    private javax.swing.JButton jButtonHomePage;
    private javax.swing.JButton jButtonHotdog;
    private javax.swing.JButton jButtonKFC;
    private javax.swing.JButton jButtonMe;
    private javax.swing.JButton jButtonNotification;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonPizza;
    private javax.swing.JLabel jLabelBeer;
    private javax.swing.JLabel jLabelBubbleTea;
    private javax.swing.JLabel jLabelCart;
    private javax.swing.JLabel jLabelCategory;
    private javax.swing.JLabel jLabelCoffee;
    private javax.swing.JLabel jLabelCollection;
    private javax.swing.JLabel jLabelDealHotToday;
    private javax.swing.JLabel jLabelDelivery;
    private javax.swing.JLabel jLabelDiscountCode;
    private javax.swing.JLabel jLabelException1MainView;
    private javax.swing.JLabel jLabelFavorite;
    private javax.swing.JLabel jLabelFreeshipXtra;
    private javax.swing.JLabel jLabelHamburger;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelHotdog;
    private javax.swing.JLabel jLabelKFC;
    private javax.swing.JLabel jLabelMe;
    private javax.swing.JLabel jLabelNotification;
    private javax.swing.JLabel jLabelOrder;
    private javax.swing.JLabel jLabelOut;
    private javax.swing.JLabel jLabelPizza;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelrBread;
    private javax.swing.JPanel jPanelFooter;
    private javax.swing.JPanel jPanelMainBody;
    private javax.swing.JPanel jPanelMainView;
    private javax.swing.JTextField jTextFieldPosition;
    // End of variables declaration//GEN-END:variables
}
