/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import static View.Manager.checkPayedorNotQR;
import static View.Manager.jFrameMain;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author min
 */
public class QRCartView extends javax.swing.JInternalFrame {

    /**
     * Creates new form QRCartView
     */
    private Manager mng;
    public QRCartView() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelQR = new javax.swing.JPanel();
        jButtonPaymentQRCartView = new javax.swing.JButton();
        jTextFieldNameCartView = new javax.swing.JTextField();
        jTextFieldPhoneNumberCartView = new javax.swing.JTextField();
        jLabelNameCartView = new javax.swing.JLabel();
        jLabelPhoneNumberCartView = new javax.swing.JLabel();
        jTextFieldGmailQRCartView = new javax.swing.JTextField();
        jLabelGmailQRCartView = new javax.swing.JLabel();
        jButtonCheckBilIQRCartView = new javax.swing.JButton();
        jLabelHeaderCartView = new javax.swing.JLabel();
        jLabelAddressQRCartView = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddressQRCartView = new javax.swing.JTextArea();
        jLabelImageQRQRCartView = new javax.swing.JLabel();

        jPanelQR.setBackground(new java.awt.Color(255, 255, 255));

        jButtonPaymentQRCartView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonPaymentQRCartView.setText("Thanh toán");
        jButtonPaymentQRCartView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPaymentQRCartViewActionPerformed(evt);
            }
        });

        jTextFieldNameCartView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldPhoneNumberCartView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelNameCartView.setText("Họ và tên");

        jLabelPhoneNumberCartView.setText("Số điện thoại");

        jTextFieldGmailQRCartView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabelGmailQRCartView.setText("Gmail");

        jButtonCheckBilIQRCartView.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCheckBilIQRCartView.setText("Xem hóa đơn");
        jButtonCheckBilIQRCartView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCheckBilIQRCartViewActionPerformed(evt);
            }
        });

        jLabelHeaderCartView.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelHeaderCartView.setText("     Thông tin thanh toán");

        jLabelAddressQRCartView.setText("Địa chỉ");

        jTextAreaAddressQRCartView.setColumns(20);
        jTextAreaAddressQRCartView.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddressQRCartView);

        jLabelImageQRQRCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/QRMe.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelQRLayout = new javax.swing.GroupLayout(jPanelQR);
        jPanelQR.setLayout(jPanelQRLayout);
        jPanelQRLayout.setHorizontalGroup(
            jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQRLayout.createSequentialGroup()
                .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQRLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabelImageQRQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonCheckBilIQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonPaymentQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelQRLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldNameCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanelQRLayout.createSequentialGroup()
                                    .addComponent(jLabelNameCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(365, 365, 365)))
                            .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelQRLayout.createSequentialGroup()
                                    .addComponent(jLabelPhoneNumberCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(22, 22, 22)
                                    .addComponent(jTextFieldPhoneNumberCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelQRLayout.createSequentialGroup()
                                    .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelAddressQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelGmailQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldGmailQRCartView, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2))))))
                    .addGroup(jPanelQRLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabelHeaderCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanelQRLayout.setVerticalGroup(
            jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelQRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeaderCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameCartView))
                .addGap(18, 18, 18)
                .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumberCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPhoneNumberCartView))
                .addGap(18, 18, 18)
                .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGmailQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGmailQRCartView))
                .addGap(18, 18, 18)
                .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddressQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelQRLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelQRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCheckBilIQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPaymentQRCartView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelQRLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabelImageQRQRCartView)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelQR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCheckBilIQRCartViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCheckBilIQRCartViewActionPerformed
        // TODO add your handling code here:
        this.mng.jPanelCartView.setVisible(false);
        if (this.mng.checkBill == 1){
            jFrameMain.add(this.mng.jPanelBillView);
            this.mng.checkBill = 2;
        }
        System.out.println("hello xin chao");
        mng.jPanelBillView.setVisible(true);
        this.mng.jFrameMain.setSize(885, 650);
        this.mng.checkCartViewOrMainView =1;
        this.mng.jFrameMain.getContentPane().setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonCheckBilIQRCartViewActionPerformed

    private void jButtonPaymentQRCartViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPaymentQRCartViewActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNameCartView.getText().equals("") || jTextFieldPhoneNumberCartView.getText().equals("") || jTextFieldGmailQRCartView.getText().equals("")|| jTextAreaAddressQRCartView.getText().equals("")){
            JOptionPane.showMessageDialog(jFrameMain,"Chưa điền đủ thông tin!","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(jFrameMain,"Thanh toán thành công!","Accept",JOptionPane.INFORMATION_MESSAGE);         
            mng.checkPayedorNotQR=1;
            mng.varUpdateTransactionQR =             "    Thông tin người dùng thanh toán\n"
                                                    +"    Tên: "+jTextFieldNameCartView.getText() +"\n"
                                                    +"    Số điện thoại: "+jTextFieldPhoneNumberCartView.getText()
                                                    +"    Gmail: "+jTextFieldGmailQRCartView.getText()+"\n"
                                                    +"    Địa chỉ: "+jTextAreaAddressQRCartView.getText()+"\n"
                                                    +"    Loại hình thanh toán: quét mã QR\n";
        }
    }//GEN-LAST:event_jButtonPaymentQRCartViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheckBilIQRCartView;
    private javax.swing.JButton jButtonPaymentQRCartView;
    private javax.swing.JLabel jLabelAddressQRCartView;
    private javax.swing.JLabel jLabelGmailQRCartView;
    private javax.swing.JLabel jLabelHeaderCartView;
    private javax.swing.JLabel jLabelImageQRQRCartView;
    private javax.swing.JLabel jLabelNameCartView;
    private javax.swing.JLabel jLabelPhoneNumberCartView;
    private javax.swing.JPanel jPanelQR;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaAddressQRCartView;
    private javax.swing.JTextField jTextFieldGmailQRCartView;
    private javax.swing.JTextField jTextFieldNameCartView;
    private javax.swing.JTextField jTextFieldPhoneNumberCartView;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonCheckBilIQRCartView() {
        return jButtonCheckBilIQRCartView;
    }

    public void setjButtonCheckBilIQRCartView(JButton jButtonCheckBilIQRCartView) {
        this.jButtonCheckBilIQRCartView = jButtonCheckBilIQRCartView;
    }

    public JTextField getjTextFieldNameCartView() {
        return jTextFieldNameCartView;
    }

    public void setjTextFieldNameCartView(JTextField jTextFieldNameCartView) {
        this.jTextFieldNameCartView = jTextFieldNameCartView;
    }
    
    
}
