/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author min
 */
public class UserView extends javax.swing.JFrame {

    /**
     * Creates new form UserView
     */
    //206, 699
    public UserView() {
        initComponents();
    }
    int width = 206;
    int height = 699;

    private void openMenuBar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < width; i++) {
                    jPanelVerticalUserView.setSize(i, height);
                    //mở từ từ
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    private void closeMenuBar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = width; i > 0; i--) {
                    jPanelVerticalUserView.setSize(i, height);
                    // đóng từ từ
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(UserView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelUserView = new javax.swing.JPanel();
        jPanelVerticalUserView = new javax.swing.JPanel();
        jLabelImageUserView = new javax.swing.JLabel();
        jSeparatorImageUserView = new javax.swing.JSeparator();
        jPanelInfoAccountUserView = new javax.swing.JPanel();
        jLabelInfoAccountUserView = new javax.swing.JLabel();
        jPanelLikeUserView = new javax.swing.JPanel();
        jLabelLikeUserView = new javax.swing.JLabel();
        jPanelTransactionHistoryUserView = new javax.swing.JPanel();
        jLabelTransactionHistoryUserView = new javax.swing.JLabel();
        jLabelCloseBarUserView = new javax.swing.JLabel();
        jPanelContainerUserView = new javax.swing.JPanel();
        jPanelInforAccountMainUserView = new javax.swing.JPanel();
        jLabelEmailUserView = new javax.swing.JLabel();
        jLabelPasswordUserView = new javax.swing.JLabel();
        jLabelInfoSignInUserView = new javax.swing.JLabel();
        jLabelNameUserView = new javax.swing.JLabel();
        jLabelGenderUserView = new javax.swing.JLabel();
        jLabelBirthUserView = new javax.swing.JLabel();
        jLabelJobUserView = new javax.swing.JLabel();
        jButtonUpdateInfoUserView = new javax.swing.JButton();
        jTextFieldPasswordUserView = new javax.swing.JTextField();
        jTextFieldNameUserView = new javax.swing.JTextField();
        jTextFieldEmailUserView = new javax.swing.JTextField();
        jTextFieldBirthUserView = new javax.swing.JTextField();
        jTextFieldGenderUserView = new javax.swing.JTextField();
        jTextFieldJobUserView = new javax.swing.JTextField();
        jSeparatorTextInfoSignInUserView = new javax.swing.JSeparator();
        jPanelLikeMainUserView = new javax.swing.JPanel();
        jLabelTextLikeUserView = new javax.swing.JLabel();
        jScrollPaneLikeUserView = new javax.swing.JScrollPane();
        jTextAreaLikeUserView = new javax.swing.JTextArea();
        jSeparatorTextLikeUserView = new javax.swing.JSeparator();
        jPanelTransactionHistoryMainUserView = new javax.swing.JPanel();
        jScrollPaneBillView = new javax.swing.JScrollPane();
        jTextAreaTransactionUserView = new javax.swing.JTextArea();
        jLabelTextTransactionUserView = new javax.swing.JLabel();
        jButtonDeleteHistoryOfTransactionHistoryUserView = new javax.swing.JButton();
        jPanelHorizonMainUserView = new javax.swing.JPanel();
        jLabelMenuUserView = new javax.swing.JLabel();
        jButtonBackUserView = new javax.swing.JButton();
        jLabelNameAppUserView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelUserView.setBackground(new java.awt.Color(255, 153, 51));

        jPanelVerticalUserView.setBackground(new java.awt.Color(13, 36, 51));

        jLabelImageUserView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Desktop\\icons8-user.gif")); // NOI18N

        jPanelInfoAccountUserView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInfoAccountUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelInfoAccountUserViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelInfoAccountUserViewMousePressed(evt);
            }
        });

        jLabelInfoAccountUserView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelInfoAccountUserView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelInfoAccountUserView.setForeground(new java.awt.Color(102, 255, 0));
        jLabelInfoAccountUserView.setText("            Thông tin tài khoản");
        jLabelInfoAccountUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInfoAccountUserViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelInfoAccountUserViewLayout = new javax.swing.GroupLayout(jPanelInfoAccountUserView);
        jPanelInfoAccountUserView.setLayout(jPanelInfoAccountUserViewLayout);
        jPanelInfoAccountUserViewLayout.setHorizontalGroup(
            jPanelInfoAccountUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoAccountUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );
        jPanelInfoAccountUserViewLayout.setVerticalGroup(
            jPanelInfoAccountUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelInfoAccountUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        jPanelLikeUserView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelLikeUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLikeUserViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelLikeUserViewMousePressed(evt);
            }
        });

        jLabelLikeUserView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelLikeUserView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelLikeUserView.setForeground(new java.awt.Color(255, 0, 51));
        jLabelLikeUserView.setText("                    Yêu thích");
        jLabelLikeUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLikeUserViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLikeUserViewLayout = new javax.swing.GroupLayout(jPanelLikeUserView);
        jPanelLikeUserView.setLayout(jPanelLikeUserViewLayout);
        jPanelLikeUserViewLayout.setHorizontalGroup(
            jPanelLikeUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLikeUserView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLikeUserViewLayout.setVerticalGroup(
            jPanelLikeUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLikeUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanelTransactionHistoryUserView.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTransactionHistoryUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelTransactionHistoryUserViewMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelTransactionHistoryUserViewMousePressed(evt);
            }
        });

        jLabelTransactionHistoryUserView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelTransactionHistoryUserView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTransactionHistoryUserView.setForeground(new java.awt.Color(255, 153, 51));
        jLabelTransactionHistoryUserView.setText("              Lịch sử giao dịch");
        jLabelTransactionHistoryUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransactionHistoryUserViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransactionHistoryUserViewLayout = new javax.swing.GroupLayout(jPanelTransactionHistoryUserView);
        jPanelTransactionHistoryUserView.setLayout(jPanelTransactionHistoryUserViewLayout);
        jPanelTransactionHistoryUserViewLayout.setHorizontalGroup(
            jPanelTransactionHistoryUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransactionHistoryUserViewLayout.createSequentialGroup()
                .addComponent(jLabelTransactionHistoryUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanelTransactionHistoryUserViewLayout.setVerticalGroup(
            jPanelTransactionHistoryUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTransactionHistoryUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jLabelCloseBarUserView.setBackground(new java.awt.Color(13, 36, 51));
        jLabelCloseBarUserView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCloseBarUserView.setForeground(new java.awt.Color(0, 0, 255));
        jLabelCloseBarUserView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-back-64.png"))); // NOI18N
        jLabelCloseBarUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseBarUserViewMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelVerticalUserViewLayout = new javax.swing.GroupLayout(jPanelVerticalUserView);
        jPanelVerticalUserView.setLayout(jPanelVerticalUserViewLayout);
        jPanelVerticalUserViewLayout.setHorizontalGroup(
            jPanelVerticalUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparatorImageUserView)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerticalUserViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelImageUserView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCloseBarUserView))
            .addGroup(jPanelVerticalUserViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerticalUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLikeUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerticalUserViewLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanelTransactionHistoryUserView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelVerticalUserViewLayout.createSequentialGroup()
                        .addComponent(jPanelInfoAccountUserView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVerticalUserViewLayout.setVerticalGroup(
            jPanelVerticalUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerticalUserViewLayout.createSequentialGroup()
                .addGroup(jPanelVerticalUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVerticalUserViewLayout.createSequentialGroup()
                        .addComponent(jLabelCloseBarUserView)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVerticalUserViewLayout.createSequentialGroup()
                        .addComponent(jLabelImageUserView)
                        .addGap(39, 39, 39)))
                .addComponent(jSeparatorImageUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanelInfoAccountUserView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelLikeUserView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelTransactionHistoryUserView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelContainerUserView.setLayout(new java.awt.CardLayout());

        jPanelInforAccountMainUserView.setBackground(new java.awt.Color(255, 204, 204));
        jPanelInforAccountMainUserView.setForeground(new java.awt.Color(255, 204, 204));

        jLabelEmailUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelEmailUserView.setText("Email:");

        jLabelPasswordUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPasswordUserView.setText("Mật khẩu:");

        jLabelInfoSignInUserView.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelInfoSignInUserView.setText("Thông tin đăng nhập");

        jLabelNameUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNameUserView.setText("Tên:");

        jLabelGenderUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelGenderUserView.setText("Giới tính:");

        jLabelBirthUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBirthUserView.setText("Ngày sinh:");

        jLabelJobUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelJobUserView.setText("Nghề nghiệp:");

        jButtonUpdateInfoUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButtonUpdateInfoUserView.setText("Cập nhật thông tin");
        jButtonUpdateInfoUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateInfoUserViewActionPerformed(evt);
            }
        });

        jTextFieldPasswordUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPasswordUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordUserViewActionPerformed(evt);
            }
        });

        jTextFieldNameUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldEmailUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldEmailUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailUserViewActionPerformed(evt);
            }
        });

        jTextFieldBirthUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldBirthUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBirthUserViewActionPerformed(evt);
            }
        });

        jTextFieldGenderUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextFieldJobUserView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jSeparatorTextInfoSignInUserView.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanelInforAccountMainUserViewLayout = new javax.swing.GroupLayout(jPanelInforAccountMainUserView);
        jPanelInforAccountMainUserView.setLayout(jPanelInforAccountMainUserViewLayout);
        jPanelInforAccountMainUserViewLayout.setHorizontalGroup(
            jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInforAccountMainUserViewLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelInfoSignInUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(jSeparatorTextInfoSignInUserView))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInforAccountMainUserViewLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNameUserView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPasswordUserView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEmailUserView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBirthUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelGenderUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelJobUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUpdateInfoUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPasswordUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmailUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBirthUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGenderUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJobUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(260, 260, 260))
        );
        jPanelInforAccountMainUserViewLayout.setVerticalGroup(
            jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInforAccountMainUserViewLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelInfoSignInUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTextInfoSignInUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmailUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPasswordUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPasswordUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNameUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGenderUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldGenderUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldBirthUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jLabelBirthUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInforAccountMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldJobUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJobUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateInfoUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelContainerUserView.add(jPanelInforAccountMainUserView, "card2");

        jPanelLikeMainUserView.setBackground(new java.awt.Color(153, 255, 204));

        jLabelTextLikeUserView.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextLikeUserView.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelTextLikeUserView.setText("Danh sách yêu thích");

        jTextAreaLikeUserView.setColumns(20);
        jTextAreaLikeUserView.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextAreaLikeUserView.setRows(5);
        jScrollPaneLikeUserView.setViewportView(jTextAreaLikeUserView);

        javax.swing.GroupLayout jPanelLikeMainUserViewLayout = new javax.swing.GroupLayout(jPanelLikeMainUserView);
        jPanelLikeMainUserView.setLayout(jPanelLikeMainUserViewLayout);
        jPanelLikeMainUserViewLayout.setHorizontalGroup(
            jPanelLikeMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLikeMainUserViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneLikeUserView)
                .addContainerGap())
            .addGroup(jPanelLikeMainUserViewLayout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addGroup(jPanelLikeMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTextLikeUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparatorTextLikeUserView))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        jPanelLikeMainUserViewLayout.setVerticalGroup(
            jPanelLikeMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLikeMainUserViewLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTextLikeUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparatorTextLikeUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPaneLikeUserView, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
        );

        jPanelContainerUserView.add(jPanelLikeMainUserView, "card3");

        jPanelTransactionHistoryMainUserView.setBackground(new java.awt.Color(204, 204, 255));

        jTextAreaTransactionUserView.setColumns(20);
        jTextAreaTransactionUserView.setRows(5);
        jScrollPaneBillView.setViewportView(jTextAreaTransactionUserView);

        jLabelTextTransactionUserView.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTextTransactionUserView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTextTransactionUserView.setText("LỊCH SỬ GIAO DỊCH");

        jButtonDeleteHistoryOfTransactionHistoryUserView.setBackground(new java.awt.Color(255, 51, 0));
        jButtonDeleteHistoryOfTransactionHistoryUserView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonDeleteHistoryOfTransactionHistoryUserView.setText("Xóa lịch sử ");
        jButtonDeleteHistoryOfTransactionHistoryUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteHistoryOfTransactionHistoryUserViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTransactionHistoryMainUserViewLayout = new javax.swing.GroupLayout(jPanelTransactionHistoryMainUserView);
        jPanelTransactionHistoryMainUserView.setLayout(jPanelTransactionHistoryMainUserViewLayout);
        jPanelTransactionHistoryMainUserViewLayout.setHorizontalGroup(
            jPanelTransactionHistoryMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransactionHistoryMainUserViewLayout.createSequentialGroup()
                .addContainerGap(688, Short.MAX_VALUE)
                .addGroup(jPanelTransactionHistoryMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransactionHistoryMainUserViewLayout.createSequentialGroup()
                        .addComponent(jLabelTextTransactionUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTransactionHistoryMainUserViewLayout.createSequentialGroup()
                        .addComponent(jButtonDeleteHistoryOfTransactionHistoryUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(jPanelTransactionHistoryMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTransactionHistoryMainUserViewLayout.createSequentialGroup()
                    .addGap(228, 228, 228)
                    .addComponent(jScrollPaneBillView, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addGap(228, 228, 228)))
        );
        jPanelTransactionHistoryMainUserViewLayout.setVerticalGroup(
            jPanelTransactionHistoryMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTransactionHistoryMainUserViewLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabelTextTransactionUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButtonDeleteHistoryOfTransactionHistoryUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
            .addGroup(jPanelTransactionHistoryMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTransactionHistoryMainUserViewLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jScrollPaneBillView, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        jPanelContainerUserView.add(jPanelTransactionHistoryMainUserView, "card5");

        jPanelHorizonMainUserView.setBackground(new java.awt.Color(255, 153, 51));

        jLabelMenuUserView.setIcon(new javax.swing.ImageIcon("C:\\Users\\min\\Desktop\\icons8-top-menu-48.png")); // NOI18N
        jLabelMenuUserView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMenuUserViewMouseClicked(evt);
            }
        });

        jButtonBackUserView.setBackground(new java.awt.Color(255, 153, 51));
        jButtonBackUserView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close.gif"))); // NOI18N
        jButtonBackUserView.setBorder(null);
        jButtonBackUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUserViewActionPerformed(evt);
            }
        });

        jLabelNameAppUserView.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelNameAppUserView.setText(" FastFood");

        javax.swing.GroupLayout jPanelHorizonMainUserViewLayout = new javax.swing.GroupLayout(jPanelHorizonMainUserView);
        jPanelHorizonMainUserView.setLayout(jPanelHorizonMainUserViewLayout);
        jPanelHorizonMainUserViewLayout.setHorizontalGroup(
            jPanelHorizonMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHorizonMainUserViewLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabelMenuUserView)
                .addGap(190, 190, 190)
                .addComponent(jLabelNameAppUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBackUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelHorizonMainUserViewLayout.setVerticalGroup(
            jPanelHorizonMainUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHorizonMainUserViewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNameAppUserView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelHorizonMainUserViewLayout.createSequentialGroup()
                .addComponent(jButtonBackUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHorizonMainUserViewLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelMenuUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelUserViewLayout = new javax.swing.GroupLayout(jPanelUserView);
        jPanelUserView.setLayout(jPanelUserViewLayout);
        jPanelUserViewLayout.setHorizontalGroup(
            jPanelUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserViewLayout.createSequentialGroup()
                .addComponent(jPanelVerticalUserView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanelUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelContainerUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelUserViewLayout.createSequentialGroup()
                        .addComponent(jPanelHorizonMainUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanelUserViewLayout.setVerticalGroup(
            jPanelUserViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelVerticalUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelUserViewLayout.createSequentialGroup()
                .addComponent(jPanelHorizonMainUserView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelContainerUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUserView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelInfoAccountUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInfoAccountUserViewMouseClicked
        // TODO add your handling code here:
        QRCartView inCash = new QRCartView();
        //jDesktopPanelCartView.removeAll();
        //jDesktopPanelCartView.add(inCash).setVisible(true);
    }//GEN-LAST:event_jPanelInfoAccountUserViewMouseClicked

    private void jPanelInfoAccountUserViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelInfoAccountUserViewMousePressed
        // TODO add your handling code here:
        //jPanelTotalBillView.setBackground(DefaultColorCartView);
        //jPanelReceiptBillView.setBackground(clickedColorCartView);

        //jLabelWordCartView.setText("Quét mã QR");
        //jLabelImageCartView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-qr-code.gif")));
    }//GEN-LAST:event_jPanelInfoAccountUserViewMousePressed

    private void jPanelLikeUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLikeUserViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelLikeUserViewMouseClicked

    private void jPanelLikeUserViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLikeUserViewMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelLikeUserViewMousePressed

    private void jPanelTransactionHistoryUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransactionHistoryUserViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelTransactionHistoryUserViewMouseClicked

    private void jPanelTransactionHistoryUserViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelTransactionHistoryUserViewMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelTransactionHistoryUserViewMousePressed

    private void jLabelMenuUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMenuUserViewMouseClicked
        openMenuBar();
    }//GEN-LAST:event_jLabelMenuUserViewMouseClicked

    private void jLabelCloseBarUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseBarUserViewMouseClicked
        // TODO add your handling code here:
        closeMenuBar();
    }//GEN-LAST:event_jLabelCloseBarUserViewMouseClicked

    private void jLabelInfoAccountUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInfoAccountUserViewMouseClicked
        // TODO add your handling code here:
        jPanelInforAccountMainUserView.setVisible(true);
        jPanelTransactionHistoryMainUserView.setVisible(false);
        jPanelLikeMainUserView.setVisible(false);
    }//GEN-LAST:event_jLabelInfoAccountUserViewMouseClicked

    private void jLabelLikeUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLikeUserViewMouseClicked
        // TODO add your handling code here:
        jPanelInforAccountMainUserView.setVisible(false);
        jPanelTransactionHistoryMainUserView.setVisible(false);
        jPanelLikeMainUserView.setVisible(true);
    }//GEN-LAST:event_jLabelLikeUserViewMouseClicked

    private void jLabelTransactionHistoryUserViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransactionHistoryUserViewMouseClicked
        // TODO add your handling code here:
        jPanelInforAccountMainUserView.setVisible(false);
        jPanelTransactionHistoryMainUserView.setVisible(true);
        jPanelLikeMainUserView.setVisible(false);
    }//GEN-LAST:event_jLabelTransactionHistoryUserViewMouseClicked

    private void jButtonBackUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackUserViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackUserViewActionPerformed

    private void jButtonUpdateInfoUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateInfoUserViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUpdateInfoUserViewActionPerformed

    private void jTextFieldEmailUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailUserViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailUserViewActionPerformed

    private void jTextFieldPasswordUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordUserViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordUserViewActionPerformed

    private void jTextFieldBirthUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBirthUserViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBirthUserViewActionPerformed

    private void jButtonDeleteHistoryOfTransactionHistoryUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteHistoryOfTransactionHistoryUserViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteHistoryOfTransactionHistoryUserViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackUserView;
    private javax.swing.JButton jButtonDeleteHistoryOfTransactionHistoryUserView;
    private javax.swing.JButton jButtonUpdateInfoUserView;
    private javax.swing.JLabel jLabelBirthUserView;
    private javax.swing.JLabel jLabelCloseBarUserView;
    private javax.swing.JLabel jLabelEmailUserView;
    private javax.swing.JLabel jLabelGenderUserView;
    private javax.swing.JLabel jLabelImageUserView;
    private javax.swing.JLabel jLabelInfoAccountUserView;
    private javax.swing.JLabel jLabelInfoSignInUserView;
    private javax.swing.JLabel jLabelJobUserView;
    private javax.swing.JLabel jLabelLikeUserView;
    private javax.swing.JLabel jLabelMenuUserView;
    private javax.swing.JLabel jLabelNameAppUserView;
    private javax.swing.JLabel jLabelNameUserView;
    private javax.swing.JLabel jLabelPasswordUserView;
    private javax.swing.JLabel jLabelTextLikeUserView;
    private javax.swing.JLabel jLabelTextTransactionUserView;
    private javax.swing.JLabel jLabelTransactionHistoryUserView;
    private javax.swing.JPanel jPanelContainerUserView;
    private javax.swing.JPanel jPanelHorizonMainUserView;
    private javax.swing.JPanel jPanelInfoAccountUserView;
    private javax.swing.JPanel jPanelInforAccountMainUserView;
    private javax.swing.JPanel jPanelLikeMainUserView;
    private javax.swing.JPanel jPanelLikeUserView;
    private javax.swing.JPanel jPanelTransactionHistoryMainUserView;
    private javax.swing.JPanel jPanelTransactionHistoryUserView;
    private javax.swing.JPanel jPanelUserView;
    private javax.swing.JPanel jPanelVerticalUserView;
    private javax.swing.JScrollPane jScrollPaneBillView;
    private javax.swing.JScrollPane jScrollPaneLikeUserView;
    private javax.swing.JSeparator jSeparatorImageUserView;
    private javax.swing.JSeparator jSeparatorTextInfoSignInUserView;
    private javax.swing.JSeparator jSeparatorTextLikeUserView;
    private javax.swing.JTextArea jTextAreaLikeUserView;
    private javax.swing.JTextArea jTextAreaTransactionUserView;
    private javax.swing.JTextField jTextFieldBirthUserView;
    private javax.swing.JTextField jTextFieldEmailUserView;
    private javax.swing.JTextField jTextFieldGenderUserView;
    private javax.swing.JTextField jTextFieldJobUserView;
    private javax.swing.JTextField jTextFieldNameUserView;
    private javax.swing.JTextField jTextFieldPasswordUserView;
    // End of variables declaration//GEN-END:variables

}
